### ISSUE TITLE
Separate $THREADS for update and render?

### ISSUE THREAD

**Issue by gevaerts** [Overv/openstreetmap-tile-server#112]
It would be nice to have separate THREADS parameters for updating and rendering. On SSD it's probably fine, but on spinning rust osm2pgsql sometimes really has to be toned down to keep the machine usable. Rendering (assuming enough RAM so database cache works well) is mostly CPU, so the numbers that work best can be very different.

**Comment by Istador** [comment]
If the [openstreetmap-tiles-update-expire](https://github.com/Overv/openstreetmap-tile-server/blob/cc5b50b050a9e68f70b15dc2ed82aa1b5082de9a/openstreetmap-tiles-update-expire#L25) script were changed to have the `OSM2PGSQL_EXTRA_ARGS` at the end, like at the [import](https://github.com/Overv/openstreetmap-tile-server/blob/cc5b50b050a9e68f70b15dc2ed82aa1b5082de9a/run.sh#L76) , this would be easily possible like so:
```
-e THREADS=8  -e "OSM2PGSQL_EXTRA_ARGS=--number-processes 4"
```

But right now, `--number-processes` is overwritten for the update by the value from `THREADS` after the `OSM2PGSQL_EXTRA_ARGS`.

**Comment by Overv** [comment]
Eh, relying on the arguments to overwrite each other seems like a hack to me. There should probably just be a separate THREADS variable that can be overwritten.

**Comment by Istador** [comment]
> Eh, relying on the arguments to overwrite each other seems like a hack to me. There should probably just be a separate THREADS variable that can be overwritten.

Yes, it is a hack. But it's not fundamentally different to all other arguments that are possible with `OSM2PGSQL_EXTRA_ARGS` which overwrite the default values of `osm2pgsql`.

I'm not against extra variables, but each additional one bloats up the documentation and makes it harder for others to read and understand the readme. Is this issue so common that it justifies an extra variable, or does a workaround with the existing variables suffice?

Nonetheless, the argument order should be the same for the `import` and for the `update`, because it differs in the things you can use `OSM2PGSQL_EXTRA_ARGS` for. Either that it allows overwriting the value from `THREADS`, or that `THREADS`/`THREADS_UPDATE` overwrites possible values from `OSM2PGSQL_EXTRA_ARGS`.
