### ISSUE TITLE
Database fails to load (confusion between postgres 10 and 12)

### ISSUE THREAD

**Issue by SomeoneElseOSM** [Overv/openstreetmap-tile-server#115]
It looks like something relatively recently has changed and something's broken.

On a Centos 7.7 system, after a recent "docker system prune -a":

docker volume create openstreetmap-data

docker run -v /home/ajtown/zambia-latest.osm.pbf:/data.osm.pbf     -v openstreetmap-data:/var/lib/postgresql/12/main     overv/openstreetmap-tile-server     import

fails with this in the standard output:

 * Starting PostgreSQL 12 database server
 * Error: /usr/lib/postgresql/12/bin/pg_ctl /usr/lib/postgresql/12/bin/pg_ctl start -D /var/lib/postgresql/12/main -l /var/log/postgresql/postgresql-12-main.log -s -o  -c config_file="/etc/postgresql/12/main/postgresql.conf"  exited with status 1: 
2020-03-28 13:47:14.256 UTC [26] FATAL:  database files are incompatible with server
2020-03-28 13:47:14.256 UTC [26] DETAIL:  The data directory was initialized by PostgreSQL version 10, which is not compatible with this version 12.1 (Ubuntu 12.1-1.pgdg18.04+1).
pg_ctl: could not start server

**Comment by Istador** [comment]
`docker system prune -a` doesn't delete volumes, and therefore it is still using the existing `openstreetmap-data` volume. If it shall delete volumes too, it's: `docker system prune --all --volumes`.

By executing `docker system prune -a` while the osm server wasn't running, you deleted the existing `latest` image on your computer. With `docker run` it downloaded the newest version of the `latest` tag. The database files that are in the `openstreetmap-data` volume, which weren't deleted, are for postgres 10 and are incompatible with postgres 12.

---

This image was upgraded to postgres 12 with [v1.3.6](https://github.com/Overv/openstreetmap-tile-server/releases/tag/v1.3.6). Such a breaking change should normally not happen in a minor version bumb from 1.3.5 to 1.3.6, but justifies a bigger version bump, e.g. from 1.3.5 to 1.4.0 or even 2.0.0.

You either need to [migrate](https://www.postgresql.org/docs/12/pgupgrade.html) the database files inside the volume, delete them and import again, or you need to use an older version than `v1.3.6`, e.g. [v1.3.5](https://github.com/Overv/openstreetmap-tile-server/releases/tag/v1.3.5).

---

It's generally advisable to use version tags. So instead of using `overv/openstreetmap-tile-server` in your docker commands, which is effectively the same as `overv/openstreetmap-tile-server:latest`, consider using e.g. `overv/openstreetmap-tile-server:1.3.10` for the currently latest version. That way you always know which version you're currently using and make updates intentionally.

**Comment by SomeoneElseOSM** [comment]
@Istador Thanks - that was the problem.  I'd assumed incorrectly that "docker system prune -a" would delete everything.
