### ISSUE TITLE
Rendering is very slow

### ISSUE THREAD

**Issue by Zemledelec** [Overv/openstreetmap-tile-server#120]
Hi! Thank you for awesome docker image!
I have an issue when tiles are being rendered very slow and leads to timeout on my map ui. But after next access to them (I suppose after caching) they are well accessible and emerging on a map. So I see only one decision is to make them caching some how. Please, could you give an advice about it, may be there is another way to make the tile accessible before caching. Thanks!

P.S. I tried to change autovacum, threads, mem etc. but noluck. I use hosting provider virtual server with SSD and 6 cores.

**Comment by Istador** [comment]
Tiles on lower zoom levels usually take longer to render per image, because they have to consider bigger areas with lots of data in it. That's why usually you want to pre-render them and only calculate higher zoom levels on the fly.

For example I pre-rendered zoom levels 0-10 worldwide, 11-16 in geographical areas my application uses and 17-18 on the fly and for about 1 km around specific POI.

See issues #15, #17 and #18.

**Comment by Zemledelec** [comment]
I mentioned it! Thank you!

**Comment by kaushikray1** [comment]
> Tiles on lower zoom levels usually take longer to render per image, because they have to consider bigger areas with lots of data in it. That's why usually you want to pre-render them and only calculate higher zoom levels on the fly.
> 
> For example I pre-rendered zoom levels 0-10 worldwide, 11-16 in geographical areas my application uses and 17-18 on the fly and for about 1 km around specific POI.
> 
> See issues #15, #17 and #18.

What's the best way to only render the geographical areas? How did you do this, Many thanks in advance.

**Comment by Istador** [comment]
> What's the best way to only render the geographical areas? How did you do this, Many thanks in advance.

`render_list` for worldwide, and `render_list_geo.pl` for specific geographic areas. The mentioned issues explain and discuss it and have examples for both.

(`render_list` could also be used for specific areas, but you'd need to calculate tile coordinates for every zoom level individually, instead of using geo coordinates, which is way easier.)
