### ISSUE TITLE
Complete noob question

### ISSUE THREAD

**Issue by tbrowder** [Overv/openstreetmap-tile-server#124]
I see three ways to do things here that seem to overlap:

+ a Makefile

+ a Bash script "run.sh"

+ a README.md file with a recipe

I have a fresh server obtained primarily to be a tile server. Which path above should I choose to get started?

Thanks for making a tough path easier!

**Comment by Istador** [comment]
The `Makefile` is afaik used by @Overv to ease building and pushing the docker image to the docker hub. It's not meant to be used directly, unless you want to build the image yourself, and even then it's not really much help.

The `run.sh` is the entrypoint of the docker image. It's not meant to be used outside of the image. It's in fact used by all the commands listed in the `README.md`.

The `README.md` is the way to go. It shows the commands to use the image.

I'd advise using the `docker-compose.yml` with `docker-compose` instead of using `docker` commands directly.

**Comment by tbrowder** [comment]
Thanks. One of the things that confused me is that in the README.md I saw 'docker run ... run'.
Should those recipes be 'docker run ... run.sh'?

**Comment by Istador** [comment]
No, that's correct.

The first `run` is for the `docker` command itself.

The second `run` at the end is the first argument for the `run.sh` entrypoint. The `run.sh` has two possible arguments: [run](https://github.com/Overv/openstreetmap-tile-server/blob/cc5b50b050a9e68f70b15dc2ed82aa1b5082de9a/run.sh#L89) or [import](https://github.com/Overv/openstreetmap-tile-server/blob/cc5b50b050a9e68f70b15dc2ed82aa1b5082de9a/run.sh#L26).

Based on the Dockerfile, that states that the [`run.sh` is its entrypoint](https://github.com/Overv/openstreetmap-tile-server/blob/cca2d00a78bdff152a915fba80131166cbb279bf/Dockerfile#L181), it defaults to something like:
```
docker run [...] --entrypoint=/run.sh overv/openstreetmap-tile-server run
```
Which is basically executing:
```
/run.sh run
```

**Comment by tbrowder** [comment]
Ah, I missed the 'Dockerfile' (I did mention I have limited docker experience).

So the Dockerfile is used to build the docker container we call in the README.

**Comment by Istador** [comment]
The Dockerfile is the aggregation of commands, that if executed, form the runtime environment and also some environment configuration (default ports, environment variables, entrypoint, command, etc.).

The Dockerfile is build into an docker image. The image consists of the file system and configuration needed to run it. Dockerfiles are build up on each other, if you take a look at the Dockerfile, [you see](https://github.com/Overv/openstreetmap-tile-server/blob/cca2d00a78bdff152a915fba80131166cbb279bf/Dockerfile#L1) that it extends the official `ubuntu:18.04` docker image. You get a chain of images. In fact every single command in the Dockerfile is creating a new layer that could be on its own. Each layer consists of the changes to the filesystem done by it. Some layers are bigger than others.

The image is tagged and pushed to [docker hub](https://hub.docker.com/r/overv/openstreetmap-tile-server/), and can be pulled by everyone. So that not everyone has to build it (which is non-deterministic, because it is using internet resources and might be influenced by the build computer).

When you `docker run` an image (immutable), it creates a new container (mutable) on the local computer. Each container has its own virtual file system that contains all files with changes done to it. You can have several containers for the same image, and they can all be started, stopped and deleted individually, running at the same time.

Additionally, what's happening here with the commands in the README, is that it mounts volumes into the file system of the container. So that some directories aren't part of the container, but somewhere else (either in the filesystem of the host computer or in virtual filesystems managed by docker). That way the container that runs the `import` command, creates the database and the database files are stored in the volume and not in the container. The other container that executes the `run` command is using then the same volume and the already created database files to start the database. That way the files can be used by other containers and aren't lost when the container is deleted.

**Comment by tbrowder** [comment]
On Fri, Apr 17, 2020 at 09:05 Robin C. Ladiges <notifications@github.com>
wrote:

> The Dockerfile is the aggregation of commands, that if executed, form the
> runtime environment and also some environment configuration (default ports,
> environment variables, entrypoint, command, etc.).
>
...

Thanks so much for a very thorough explanation, Robin. And I'll look into
what is available on docker hub. If need be, I'll probably try to build a
Debian 10 (Buster) equivalent.

**Comment by Istador** [comment]
Take a look at [switch2osm](https://switch2osm.org/serving-tiles/), especially the guide to [manually build it](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-18-04-lts/). It explains the steps that are in the Dockerfile, because this project was created based on the guide. (To have a reusable easy to use dockerized version, without everyone having to deal with building it. Setting it up, configuring it, importing and running it, is even a challenge on its own.)

**Comment by tbrowder** [comment]
Thanks very much. In my quest for running a tile server on Debian Buster, would you consider having something like a "contrib" section for other host types?

**Comment by oleo65** [comment]
There is simply no need for different base images at this point. You can perfectly run a Docker image which was based on e.g. Ubuntu:18.04 on a host system running Debian Buster.

This is one of the nice abstractions Docker is doing for you.
