### ISSUE TITLE
render_list error

### ISSUE THREAD

**Issue by gareth-johnstone** [Overv/openstreetmap-tile-server#132]
Another attempt, another error sadly :(

So, re-installed the server, imported Europe, and I'm getting the following when running the render_list (to pre-render)

`rendering failed with command 4, pausing.`

There is also a small handful of tiles actually showing, the rest are showing 404 errors.

See example here: http://77.68.110.150/

**Comment by Istador** [comment]
The output of `render_list` only contains the message that there was an error, because it delegates the task of rendering to the `renderd` service of `mod_tile` that was started by the `run` command.

Please check the `docker log` of the container. It contains the output of the `renderd` service, which should contain errors happening during rendering.
