### ISSUE TITLE
Changes in upstream (openstreetmap-carto) break this build

### ISSUE THREAD

**Issue by Gaibhne** [Overv/openstreetmap-tile-server#138]
The referenced file `scripts/get-shapefiles.py` does not exist in upstream anymore, leading to the Docker build breaking.

**Comment by asalz-zh** [comment]
@Gaibhne 
Did you ever find a workaround?

**Comment by Overv** [comment]
I cannot reproduce this problem with a clean Docker build.

**Comment by Istador** [comment]
The [current Dockerfile](https://github.com/Overv/openstreetmap-tile-server/blob/bcf2cfcadada1340b05e517e1f629b642915837a/Dockerfile#L127) is checking out the specific tag `v4.23.0` which [contains the file](https://github.com/gravitystorm/openstreetmap-carto/blob/v4.23.0/scripts/get-shapefiles.py).

This should not be a problem currently, since commit bfcc7d7c44d3dd0bc72aefba6d39f5fbd95eae28. It is a problem if you'd try to build an old version of this project before this commit. It'd also be a problem if we'd try to update osm carto to a newer version in the Dockerfile. Then it'd have to be adapted in order to work.
