### ISSUE TITLE
Importing Europe REALLY slow

### ISSUE THREAD

**Issue by gareth-johnstone** [Overv/openstreetmap-tile-server#16]
Hi Guys,
So I'm currently importing Europe (or trying to at least)

So far its been running for 2 days:

`Processing: Node(2213933k 119.5k/s) Way(9196k 0.07k/s) Relation(0 0.00/s)`

Is my "way" part of this running rather slow? how would i speed this up

Its running on a VM with 12 cores 16gb ram and 2tb of space

**Comment by Istador** [comment]
If I remember correctly, it took me something between 10 to 20 hours to import Europe and Africa together.

---

Is your 2 TB storage on an SSD?

Does the /var/lib/docker directory of your host system also reside on this SSD?

(Because docker places the named docker volume `openstreetmap-data` for the postgres database there by default.)

---

The import command in run.sh line 30 is hardcoded to 2 GiB (the -C parameter).
Since you have 16 GB of memory available, increasing that might give a performance boost.

---

Using the `--flat-nodes` parameter for [osm2pgsql](https://wiki.openstreetmap.org/wiki/Osm2pgsql) reduces the runtime of the initial import and for later differential updates but takes up more storage space.

---

If you want to import several continents/regions it's a lot faster to combine the PBF files into one file to import them together, rather than to import one PBF file and then appending the second PBF file.

---

You might also want to take a look at issue #5

**Comment by gakowalski** [comment]
Disabling `autovacuum` in postgres.conf could help.

**Comment by gakowalski** [comment]
I've modified `run.sh` so it should import without autovacuum - [someone here reported](https://help.openstreetmap.org/questions/52672/osm2pgsql-import-disk-space-running-out-during-index-creation/52808) that it really helps and also turning off autovacuum is suggested [in some tutorials](https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/). Clone branch `master` from my repo [here ](https://github.com/pot-gov-pl/openstreetmap-tile-server/tree/master) and build the container (caution, master is *not* the default branch in my repo).

Also, I'm working on a version of the container based on PostgreSQL 11.

**Comment by stevo01** [comment]
> Hi Guys,
> So I'm currently importing Europe (or trying to at least)
> 
> So far its been running for 2 days:
> 
> `Processing: Node(2213933k 119.5k/s) Way(9196k 0.07k/s) Relation(0 0.00/s)`
> 
> Is my "way" part of this running rather slow? how would i speed this up
> 
> Its running on a VM with 12 cores 16gb ram and 2tb of space

Hi Gareth ,
is your import still running  :-)  ? Have you found a propper setup for your machine? 

Best Regards

Steffen
