### ISSUE TITLE
Is this container support Apple Silicon M1 arm ?

### ISSUE THREAD

**Issue by kentuck13** [Overv/openstreetmap-tile-server#163]
Question in the title

**Comment by Overv** [comment]
Could you elaborate on what M1 is?

**Comment by kentuck13** [comment]
> Could you elaborate on what M1 is?

sorry, updated title

**Comment by Istador** [comment]
Not natively.

As can be seen on [docker hub](https://hub.docker.com/r/overv/openstreetmap-tile-server/tags?name=latest), this project's image is only build for `linux/amd64`.

If I understand it correctly the docker support for Apple M1 is still [experimental](https://docs.docker.com/docker-for-mac/apple-m1/) and it'd need the `linux/arm64` architecture (sometimes written as `linux/arm64/v8`) for its docker images. So, if you were to pull this image you should get an error message right now, because there is no image for your platform/architecture.

---

Using QEMU you could emulate an `linux/amd64` on your hardware to run this image on your system. That's very easy, just install QEMU (natively on the system or as an [docker image](https://github.com/multiarch/qemu-user-static#getting-started)) and pass extra `--platform` parameters to your docker commands. However it'd be emulated and probably run a bit slower.

---

Another way you could go is pull this git repository on the system where you want to use it and build the image yourself for the architecture you're on:
```
git clone https://github.com/Overv/openstreetmap-tile-server.git
cd openstreetmap-tile-server
docker build -t overv/openstreetmap-tile-server .
```

The base [ubuntu base image](https://hub.docker.com/_/ubuntu?tab=tags&name=18.04) used does support the architecture, but you might run into other issues while building.

---

The best solution would be if @Overv would build and publish the image for multiple architectures. That'd allow others to run the image on systems other than `amd64` more easily.

I did multi architecture docker builds for some of my projects:
- [project 1: golang base with buildx](https://gitlab.com/Istador/gitlab-ci-orchestrator/-/blob/d118b506325acc6dc2a86ff4df2d6dd675c37eb7/build.sh)
- [project 1 (old): golang base with manually creating separate manifests and tags](https://gitlab.com/Istador/gitlab-ci-orchestrator/-/blob/eddb0eee5defda8ef628663db1560f63134cf492/build.sh)
- [project 2: debian base with buildx and .deb extraction](https://github.com/Istador/docker-alarm-clock-applet/blob/c89ab3c6ca191a105029d68b3131545657b63057/build.sh)

I had to leave out `linux/s390x` in project 2 because the build always failed, but that arch works with project 1 - depends on the application I guess and how much effort someone wants to put into optimizing/fixing it for the different architectures. The build for `linux/arm/v6` was very slow. Though I only tested the images that I builded with `amd64` and `i386` architectures.

Good step by step tutorial:
- https://medium.com/@artur.klauser/building-multi-architecture-docker-images-with-buildx-27d80f7e2408
