### ISSUE TITLE
Extrude buildings

### ISSUE THREAD

**Issue by MacaScull** [Overv/openstreetmap-tile-server#165]
Hello,

I was just wondering if it were possible to use raster tiles generated from the database and extrude buildings from those locations?
If not, is there any plan to incorporate this functionality for use alongside mapbox

**Comment by Istador** [comment]
I'm not exactly sure what you mean by "extrude buildings". Can you elaborate on this or show an example?

What do you want to achieve?
- to stronger highlight them on the raster tiles (e.g. bolder lines, more saturated color)
- have some kind of 3D effect rendered on the raster tiles
- have them as a separate layer in your application that can be interacted with
- a somewhat realistic 3D effect that changes with perspective
- some of these things only for special locations chosen by you

**Comment by MacaScull** [comment]
I want to be able to see a 3d version of each building on top of the raster tile somewhat like this fro 3d buildings (https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/), though I have raster tiles as I am unable to produce mbtiles within the mapbox format. I was wonderinng if there was a way to grab data produced about the buildings from the DB or something to them use that data to then extruded them from the map, whether this is on another layer or not

**Comment by Istador** [comment]
In order to have such an perspective 3d effect, the client in the browser has to have the buildings as vector data.

You might want to have a look at issue #123. I haven't played around with it more as can be seen in the issue, and maybe there are easier ways, but in theory it should be possible to hook a client software (mapbox, leaflet) to the buildings' vector data exposed by tegola to render them in the browser.

If you find a way feel free to share it here.

**Comment by MacaScull** [comment]
Would it be possible to get a full setup guide for this just to get tegola working alongside this openstreetmap tile server, Ive tried a few things to get this working through docker now and havent had any luck.

How can I set this and tegola up on docker without them both just exiting before theyre built and running? Do I have to expose the DB so tegola can access it?

**Comment by MacaScull** [comment]
Update: Ive managed to get past the issue I was having in my last comment, though now when I try to run the docker image I get this error within the docker logs "Error: read /opt/tegola_config/config.toml: is a directory", im confused about the actual file structure here now as Ive moved my config file around and tried running it in different areas and again nothing has seemed to work.

**Comment by Istador** [comment]
> Would it be possible to get a full setup guide for this just to get tegola working alongside this openstreetmap tile server, Ive tried a few things to get this working through docker now and havent had any luck.
> 
> How can I set this and tegola up on docker without them both just exiting before theyre built and running? Do I have to expose the DB so tegola can access it?

My comment in the other issue is the whole installation and configuration of the osm tile server and tegola together. Just install `docker`, install `docker-compose` (requires `python` - `pip install docker-compose`), and then run the commands to import the database and run the services.

You likely tried to run this additionally to your already running server? If that's without docker-compose, or using another docker-compose file, then tegola runs in a different docker network and has no access to the postgresql database inside of the tile server container (which could be fixed by adding tegola to the other existing network). But if both is inside of the same `docker-compose.yml` file, like in the configuration I've posted, both know each other and have access to their exposed ports.

Compared to back then, when I posted the proof of concept example, I'd do the following changes (back then the `DOWNLOAD_PBF` stuff for my example wasn't published in docker hub, so I had to build it from the sources, but that's no longer the case now).

Change
```
    build: ./openstreetmap-tile-server/
    #image: overv/openstreetmap-tile-server:1.3.11
```
to:
```
    image: overv/openstreetmap-tile-server:1.5.0
```

(And maybe also update tegola to the `v0.12.1` tag while being at it.)

And not run:
```
# clone and build this project, because the newest version isn't on docker hub yet
git  clone  https://github.com/Overv/openstreetmap-tile-server
docker-compose  build
```

I just tried that out in a new VM (Linux Debian 10) and it works without problems.

> When I try to use some of the command provided like "docker-compose run tiles import", i get the error "standard_init_linux.go:219: exec user process caused: no such file or directory", im doing this on a windows machine, will this be a problem or is something else going wrong?

This sounds like a windows problem with line endings:
- https://stackoverflow.com/questions/51508150/standard-init-linux-go190-exec-user-process-caused-no-such-file-or-directory

Likely you cloned the git project and builded it with `docker-compose build` like in my post in the other issue. But while cloning the repository, it checked out the files with wrong line endings depending on your global `core.autocrlf` git config, or the `run.sh` file doesn't have the executable bit set?

Please try it again with the above recommended changes.

---

> Update: Ive managed to get past the issue I was having in my last comment, though now when I try to run the docker image I get this error within the docker logs "Error: read /opt/tegola_config/config.toml: is a directory", im confused about the actual file structure here now as Ive moved my config file around and tried running it in different areas and again nothing has seemed to work.

Then the `tegola` service at some point likely ran once without the `tegola.toml` being present (or some other problem with the volume mount - very likely because you are on windows, it's a known issue with docker on windows to be causing problems with volume mounts a lot). And because it was not present as a file, it defaulted to creating an empty directory. And now it tries to mount a file from the host system onto a directory inside the container and fails.

Throw away the tegola container and recreate it from scratch (`docker-compose rm  --force  --stop  -v  tegola` && docker-compose up -d tegola).

**Comment by MacaScull** [comment]
Hello again, Ive managed to merge theses docker images together to work in unison to provide raster tiles and vector data for my building. I was just wondering if there was a way to monitor the performance and if this method of monitoring could be replicated if I were to retrieve the entire map data in vector form form tegola rather than using the raster tiles provided with your tile server?

So far Ive been using the performance tab on chrome with is somewhat useful but isnt a great way to define performance changes when connecting to a server or database, I can visibly see the vector data struggling to be loaded whereas with the raster tiles they are almost instantaneous, do you have any advice for this type of performance monitoring?

**Comment by Istador** [comment]
> Hello again, Ive managed to merge theses docker images together to work in unison to provide raster tiles and vector data for my building. I was just wondering if there was a way to monitor the performance and if this method of monitoring could be replicated if I were to retrieve the entire map data in vector form form tegola rather than using the raster tiles provided with your tile server?

I did monitor my server with `munin` installed on the host. By default it ships with monitoring scripts for `apache` and `postgresql` - which need additional configuration to connect to docker. And I also found somewhere compatible scripts for `mod_tile` (the Mapnik raster renderer) that showed me stuff like how much time it spend rendering which zoom levels, which zoom levels were accessed the most, etc.

> I can visibly see the vector data struggling to be loaded whereas with the raster tiles they are almost instantaneous, do you have any advice for this type of performance monitoring?

The raster tile server can also be seen struggling when rendering new areas, especially on lower zoom levels. But once it did render a tile, the image is saved to the server's file system, which can be accessed relatively fast later without much computations. The indexes in the database are optimized for Mapnik tile rendering with the osm carto style and not for tegola (custom queries that you define in the configuration). Tegola has some configuration options for caching (e.g. to store in a cloud with a CDN), so that might be an approach to pursue. I'm not aware if there's a way to `pre-render` tegola. With the current configuration it should already cache data in the filesystem (but in `/tmp/` where it's lost on restarts).

Questions regarding [tegola](https://github.com/go-spatial/tegola) configuration, performance, and monitoring are probably better be asked there. Tegola is not in the scope of this project.

**Comment by MacaScull** [comment]
By any chance have you extruded buildings before in a mapbox style and accessed the height variable in the tags column of the data produced by the gis database? if so could you give some guidance on how to access it.

**Comment by Istador** [comment]
No, I have only worked with Leafpad, no Mapbox at all yet.

Apart from the tegola proof of concept, I've only played around with buildings during Mapnik rendering. I highlighted specific buildings that roughly map the geo coordinates of the POI of my application.

(I imported the coordinates into a custom table of the database, executed a geospatial query to find the nearest buildings at those coordinates, and put their osm_id into a second custom table with index, which would be used in a query during rendering, to draw an additional building layer in another color).

---

If I've seen correctly, the height and other tags should all be included inside of the vector data that tegola offers.

(BTW: another small performance optimization would be to only expose those tags and attributes that you need for your application and not everything there is. You can do that by changing the sql query inside of the `tegola.toml`.)

I can only guide you to the documentation:
- https://wiki.openstreetmap.org/wiki/Simple_3D_Buildings
- https://wiki.openstreetmap.org/wiki/Key:height
- https://wiki.openstreetmap.org/wiki/Key:min_height
- https://wiki.openstreetmap.org/wiki/Key:est_height
- https://wiki.openstreetmap.org/wiki/Key:building:levels
- https://wiki.openstreetmap.org/wiki/Key:building:min_level

The documentation of `height` suggests that there might be invalid data or different formats and units in those fields, watch out for that:
- `height=4`
- `height=4 m`
- `height=7'4"`

Keep in mind that an OSM building might have all of those attributes, none of them, or only some of them. Maybe there are even other attributes that might help you. If a concrete `height` is missing, you could use `building:levels`, if available, to estimate the height. You likely want to define some default height as a fallback for all buildings without enough data. If one building without data is touching another one with data, it might be reasonable to assume that they have an equal height.

You could even do all this logic, dealing with all those different tags, estimations, calculations and default values on the query level, so that tegola always returns `height` and `min_height` for all buildings, regardless of what they really have as values.
