### ISSUE TITLE
Using mod_tile from SomeoneElseOSM instead of openstreetmap

### ISSUE THREAD

**Issue by tajchert** [Overv/openstreetmap-tile-server#172]
Why in Dockerfile this image is using [SomeoneElseOSM/mod_tile](https://github.com/SomeoneElseOSM/mod_tile/) instead of [openstreetmap/mod_tile](https://github.com/openstreetmap/mod_tile/)? 
This might be an obvious question but I couldn't find the answer. SomeoneElseOSM seems not to be updated for a while now 
the last commit on branch `switch2osm` is from 09.2018 while `openstreetmap/mod_tile` is much more active.
Is there any reason why we should stick with old fork? Maybe it will make sense to change to openstreetmap (as a future PR/milestone), but I'm not sure where are advantages of using `SomeoneElseOSM`(sorry, I couldn't find any explanation on this) and how this change will affect the whole image.

**Comment by Overv** [comment]
It's the way it is because of the [original instructions](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-18-04-lts/):

>Next, we’ll install mod_tile and renderd. “mod_tile” is an Apache module that handles requests for tiles; “renderd” is a daemon that actually renders tiles when “mod_tile” requests them. We’ll use the “switch2osm” branch of https://github.com/SomeoneElseOSM/mod_tile, which is itself forked from https://github.com/openstreetmap/mod_tile, but modified so that it supports Ubuntu 18.04, and with a couple of other changes to work on a standard Ubuntu server rather than one of OSM’s rendering servers.

With that said, I don't know exactly what these changes are and if it's easy to switch back to the original repo.

**Comment by tajchert** [comment]
Thanks for response.
This is a bit funny because inside same instruction but for [Ubuntu 20.04](https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/) it is mentioned:

> which is itself forked from https://github.com/openstreetmap/mod_tile, but modified so that it supports Ubuntu 20.04, and with a couple of other changes to work on a standard Ubuntu server rather than one of OSM’s rendering servers.

Which probably is not true as SomeoneElseOSM/mod_tile wasn't updated since 18.04 to 20.04 so it seems like nobody is checking that instruction on each step with new Ubuntu LTS release but it is more find&replace all, and this fork was never check if it is still needed.

Looking at https://github.com/openstreetmap/mod_tile/issues/233#issuecomment-781225919 it seems official repo should work well on Ubuntu 20.04 and it might be a old instruction entry that nobody noticed.

**Comment by SomeoneElseOSM** [comment]
> Which probably is not true as SomeoneElseOSM/mod_tile wasn't updated since 18.04 to 20.04 so it seems like nobody is checking that instruction on each step with new Ubuntu LTS release but it is more find&replace all, and this fork was never check if it is still needed.

(cough) citation needed (cough)

https://github.com/SomeoneElseOSM/mod_tile/tree/switch2osm _was_ tested as https://switch2osm.org/serving-tiles/manually-building-a-tile-server-20-04-lts/ was being written, it just didn't need any changes.

With regard to the original question:

> Why in Dockerfile this image is using SomeoneElseOSM/mod_tile instead of openstreetmap/mod_tile?

It'd be absolutely possible to switch from one to the other.  Many of the changes are the same, just made to both repositories in parallel.  At some point I'll want to update https://github.com/SomeoneElseOSM/mod_tile/tree/master from its parent, and apply any remaining changes between the old https://github.com/SomeoneElseOSM/mod_tile/tree/master and the current https://github.com/SomeoneElseOSM/mod_tile/tree/switch2osm .  Those changes could also be made within the Dockerfile here, so that it starts from https://github.com/openstreetmap/mod_tile .

Note also that, for the longer term, https://switch2osm.org/serving-tiles/manually-building-a-tile-server-debian-11/ already uses the distribution's version of mod_tile.  I'd expect that the next Ubuntu LTS version would too.

**Comment by nielsole** [comment]
We now use the version installed via Ubuntu renderd package https://github.com/Overv/openstreetmap-tile-server/blob/005fe6968f8981e06d8b71b11da98e4d82556fc2/Dockerfile#L71
