### ISSUE TITLE
Internet connection to use offline tile server

### ISSUE THREAD

**Issue by sinusx1986** [Overv/openstreetmap-tile-server#173]
Hello! 

I'm trying to start server offline inside docker on VM ubuntu 18.04 on VMWare Workstation
I use bridged connection to my host (Windows 10 )
After I have been successfully imported malta.osm.pbf and run it  by docker-compose up
I can not see map inside browser until I have enabled ethernet connection. 
Once it happend, map will appear in browser, and then I can turn my connection off and continue use it offline.
Is it possible to import map and run server fully offline?

my docker-compose: 
===
version: '3'

services:
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - openstreetmap-data:/var/lib/postgresql/12/main
      - openstreetmap-rendered-tiles:/var/lib/mod_tile
    ports:
      - "8080:80"
    command: "run"

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:
===
 I have just added volume openstreetmap-rendered-tiles:/var/lib/mod_tile

**Comment by Overv** [comment]
This is most likely happening because Leaflet needs to be loaded from the CDN. If add the following two as local files then you should be able to use the tile server without any internet connection:

* https://unpkg.com/leaflet@1.3.1/dist/leaflet.css
* https://unpkg.com/leaflet@1.3.1/dist/leaflet.js

One way to do this:

1. Download the two files mentioned above to the root of this repository (place them next to `leaflet-demo.html`).
2. Change the line https://github.com/Overv/openstreetmap-tile-server/blob/master/Dockerfile#L147 to something like this:
```Dockerfile
COPY leaflet-demo.html /var/www/html/index.html
COPY leaflet.css /var/www/html/leaflet.css
COPY leaflet.js /var/www/html/leaflet.js
```
3. Change the two lines in `leaflet-demo.html` to fetch the files locally:
```html
<link rel="stylesheet" href="leaflet.css" />
<script src="leaflet.js"></script>
```
4. Rebuild the Docker image.

**Comment by sinusx1986** [comment]
Now it works! Thank you very much!!! :)
