### ISSUE TITLE
How backup openstreetmap-tile-server docker

### ISSUE THREAD

**Issue by fakhamatia** [Overv/openstreetmap-tile-server#192]
How can I create a full backup from openstreetmap-tile-server and restore it on a different system?
I am not working with Ducker at all.
I run this once for build
``` bash
docker run -v /home/anpr/iran-latest.osm.pbf:/data.osm.pbf -v osm:/var/lib/postgresql/12/main overv/openstreetmap-tile-server import
```
After run this for auto start
``` bash
docker run -p 81:80 --restart=always -v osm:/var/lib/postgresql/12/main -d overv/openstreetmap-tile-server run
```
is OK? It works ok for me
But I don't know how full backup this because I want to use this on offline ubuntu, I want to create a clone of all downloads

**Comment by Istador** [comment]
Save the docker image:
- https://stackoverflow.com/questions/48125169/how-run-docker-images-without-connect-to-internet

To copy the database files from the volume:
- https://stackoverflow.com/questions/35406213/how-to-copy-docker-volume-to-local

I guess you don't want to copy over the rendered tiles, because you don't have them in a volume?

**Comment by fakhamatia** [comment]
> Save the docker image:
> 
> * https://stackoverflow.com/questions/48125169/how-run-docker-images-without-connect-to-internet

First I save the image
```bash
docker save --output osm.tar overv/openstreetmap-tile-server
```
Then I copy the tar file to a new and offline system and:
```bash
sudo docker load --input osm.tar
```
and show me `Loaded image: overv/openstreetmap-tile-server:latest` .
`docker images` result:
``` bash
REPOSITORY                        TAG       IMAGE ID       CREATED        SIZE
overv/openstreetmap-tile-server   latest    58e9c8b5df5c   16 hours ago   2.57GB
```
But when I use `docker run` show this error :
``` bash
docker: Error response from daemon: open /var/lib/docker/volumes/osm/_data: no such file or directory
```



> I guess you don't want to copy over the rendered tiles, because you don't have them in a volume?

I did not understand.

**Comment by Istador** [comment]
> But when I use `docker run` show this error :
> 
> ```shell
> docker: Error response from daemon: open /var/lib/docker/volumes/osm/_data: no such file or directory
> ```

Well, you copied the `image` (the blueprint that is published on hub.docker.com), but not the `container` (your instance of the image with your imported data, configuration and rendered tiles).

That's what the `copy the database files from the volume` step is for. So that the database of your container that you save in the volume is copied over to the offline computer too.

Otherwise you'd need to copy over the PBF file and `import` it again on your offline computer. But that will not work, because the `import` comand requires internet connectivity to [download some resources](https://github.com/Overv/openstreetmap-tile-server/blob/9679b29b509d382f14d275e6d2c16d8d02a30daa/run.sh#L83).

> > I guess you don't want to copy over the rendered tiles, because you don't have them in a volume?
> 
> I did not understand.

The [README](https://github.com/Overv/openstreetmap-tile-server/blob/9679b29b509d382f14d275e6d2c16d8d02a30daa/README.md#preserving-rendered-tiles) of this project advises to preserve the rendered tiles (image files) by putting them into a volume like the database, so that they aren't lost when updating the image and therefore recreating the container.

Because you don't put them into a volume, I assume that you don't care about the rendered tiles and don't want to copy them over to the offline computer (so it has to render them again).

**Comment by fakhamatia** [comment]
Thanks for your patience and explanation, it works well.

```bash
#Create:
wget https://download.geofabrik.de/asia/iran-latest.osm.pbf
docker run -v /home/anpr/iran-latest.osm.pbf:/data.osm.pbf -v osm-offline:/var/lib/postgresql/12/main overv/openstreetmap-tile-server import
rm iran-latest.osm.pbf

#Backup:
docker save --output osm-offline.tar overv/openstreetmap-tile-server
CID=$(docker run -d -v osm-offline:/osm-offline busybox true)
docker cp $CID:/osm-offline ./
rar a -r osm-offline-data.rar osm-offline/
docker save --output busybox.tar busybox
docker rm $CID && sudo docker image rm busybox:latest
rm -fr osm-offline

#Restore:
sudo docker load --input osm-offline.tar
sudo docker load --input busybox.tar
CID=$(docker run -d -v osm-offline:/osm-offline busybox true)
unrar x osm-offline-data.rar
cd osm-offline
sudo docker cp . $CID:/osm-offline/
cd ../ && rm -fr osm-offline
docker rm $CID && sudo docker image rm busybox:latest
rm busybox.tar osm-offline-data.rar osm-offline.tar

#Run:
docker run -p 81:80 --restart=always -v osm-offline:/var/lib/postgresql/12/main -d overv/openstreetmap-tile-server run
```
