### ISSUE TITLE
Great lakes not rendering

### ISSUE THREAD

**Issue by JudahMorrison** [Overv/openstreetmap-tile-server#207]
I have set up a local docker osm server and it is updating properly from public osm server. However, for some reason it is not rendering two of the five great lakes. Everything else seems to be working fine.

![image](https://user-images.githubusercontent.com/66790728/129093782-0b5833f1-c1e3-4f7a-a965-2d64fdab8971.png)

Does anyone know why this is happening or how I can fix it?

**Comment by JudahMorrison** [comment]
Is there a better place to ask this question for more visibilit?

**Comment by jpylypiw** [comment]
Hey there! I am not sure if this issue is related to the docker image.
It seems like there is a issue in rendering the imported data or maybe the imported date is incorrect.
Maybe there is or was a issue when creating the database. Can you recreate the database on a second server and check if the issue is still there after import?

**Comment by JudahMorrison** [comment]
I set up another server, downloaded the latest pbf, pulled the latest docker image, and the great lakes rendered. I did the same on my production server and had the same result.
