### ISSUE TITLE
full planet prerender memory estimate?

### ISSUE THREAD

**Issue by maxim22m** [Overv/openstreetmap-tile-server#224]
Hi guys.
I'm import full planet successfully.
It's running and OK.

for pre-rendering  from zoom 0 to 10 i used this command:
`docker exec -it "container-id" render_list -a -f -n 8 -m ajt -z 0 -Z 10`
then, memory goes populated and after a while (40 min) docker container stopped with error `142 killed, service postgresql stopped`

my VM spec is:

> Compute: 16 Core
> Memory: 32 GB
> Storage: 2.1 TB SSD (SATA)

my running docker flags:
```
docker run \
    -p 8080:80 \
    -e ALLOW_CORS=enabled \
    -e THREADS=6 \
    -e "OSM2PGSQL_EXTRA_ARGS=-C 4096" \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    -v openstreetmap-rendered-tiles:/var/lib/mod_tile \
    --shm-size="512m" \
    -d overv/openstreetmap-tile-server \
    run
```

after some digging and modifying number of threads, disabling postgresql jit nothing changed and that problem is again happened.

this is my questions and glad to be answered from you, thanks:

- is 32GB memory enough for full planet? what about above spec.
- what is main cause of docker crashing with mentioned error?
- if I pre-render zoom levels separately after each done and restart docker (for releasing memory), is pre render DONE?
- if i run command with -f flag for first time, after facing error and for running that again, is not using -f flag, helps to pre-render that tiles not rendered?

**Comment by Istador** [comment]
Hmm, 32 GB should be enough in theory, though it might aquire a lot of memory. Can you reduce the amount of threads (`THREADS` as well as `-n` of `render_list`)?

```
(6 + 8) threads x 14 tables = 196 connections
196 connections x 128 MB work_mem = 24.5 GB
```

(In older posts from me you'll see a constant of `7 tables` in this calculation. This seems to have changed with newer versions of `openstreetmap-carto` because of the [external-data.yml](https://github.com/gravitystorm/openstreetmap-carto/blob/v5.3.1/external-data.yml). I just imported a new database with `v1.8.1` and it created 14 database tables.)

**Comment by maxim22m** [comment]
> 
> 
> Hmm, 32 GB should be enough in theory, though it might aquire a lot of memory. Can you reduce the amount of threads (`THREADS` as well as `-n` of `render_list`)?
> 
> ```
> (6 + 8) threads x 14 tables = 196 connections
> 196 connections x 128 MB work_mem = 25 GB
> ```
> 
> (In older posts from me you'll see a constant of `7 tables` in this calculation. This seems to have changed with newer versions of `openstreetmap-carto` because of the [external-data.yml](https://github.com/gravitystorm/openstreetmap-carto/blob/v5.3.1/external-data.yml). I just imported a new database with `v1.8.1` and it created 14 database tables.)

reducing threads no helped and using with number of 1 thread is not stop memory consumption growth.
i start prerender level by level and after memory completion and container crash start it again with same or next level without -f flag and after repeat it in close 15 turn, prerendering finished and then map working well.

**Comment by dmwharris** [comment]
I'm having problems importing the full planet successfully.  The error is "Reading in file:/data/osm.pbf.  Using PBF parser...Osm2pgsql failed due to ERROR: failed to uncompress data: data error".  The .pbf file's md5 was good, so there's no file corruption.  I'm running it with 16G memory, 4 cores and 1.5 TB storage in an Ubuntu 20 VM.  Where URL did you use to download your osm file?  What was your "docker run ...... import" command?  I used the import command provided on this site:

docker run \
    -v /home/rendereraccount/Downloads/planet-latest.osm.pbf:/data.osm.pbf \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import

**Comment by nielsole** [comment]
@dmwharris this seems unrelated to the current issue. Please open a new issue if this issue still persists.

**Comment by nielsole** [comment]
Somewhere in the OSM docs I read not to open tickets if your machines memory is < 64GB. Generally I found it helpful to add large swap partitions in memory constrained environments (rendering Europe on 16GB RAM)
