### ISSUE TITLE
What to do if the database is greater then 10GB

### ISSUE THREAD

**Issue by mpele** [Overv/openstreetmap-tile-server#232]
I have a problem when the database is greater than 10GB. I get the message:

```
Processing: Node(55193k 50.9k/s) Way(3011k 14.14k/s) Relation(0 0.0/s)2021-12-02 11:09:45  ERROR: DB copy thread failed: Ending COPY mode for 'planet_osm_polygon' failed: ERROR:  could not extend file "base/16385/17571": No space left on device
HINT:  Check free disk space.
CONTEXT:  COPY planet_osm_polygon, line 14472: "696898195 \N \N \N \N \N \N \N \N \N \N \N \N yes \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N \N..."
.
+ sudo -u postgres psql -d gis -f /home/renderer/src/openstreetmap-carto/indexes.sql
psql:/home/renderer/src/openstreetmap-carto/indexes.sql:6: ERROR:  could not extend file "base/16385/40964": No space left on device
HINT:  Check free disk space.
```

As I can see 10GB is the default docker max volume size.
I have a VPS dedicated to be a tile server and I would like Docker to use the whole available disk space. What should be the best way to set the system? Should I increase the max volume size, or mount folders directly?

**Comment by nielsole** [comment]
You can do one of two things:
* instead of using a named volume, mount a folder in the `-v` 
  `-v openstreetmap-data:/var/lib/postgresql/12/main`
  `-v /mnt/openstreetmap-data:/var/lib/postgresql/12/main` (/mnt/openstreetmap-data needs to exist of course)
* reconfigure docker to increase the limit, e.g. https://stackoverflow.com/questions/50140939/increase-docker-container-size-from-default-10gb-on-rhel7

**Comment by mpele** [comment]
Thank you !!!
