### ISSUE TITLE
Changing map language to english only?

### ISSUE THREAD

**Issue by Ilyagurm** [Overv/openstreetmap-tile-server#24]
Hi, is it possible to set it up with English only writings on the map?

**Comment by Istador** [comment]
It's partly possible.

For the [name tag](https://wiki.openstreetmap.org/wiki/Key:name) imported in the database, there often exist sub tags for translated names - but not always.

For my project I changed all mentionings of `name` in the queries in the [map style](https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml) to prefer the german name over the english name over the original name, like so:
```sql
COALESCE(tags->'name:de', tags->'name:en', name, '') as name

```

You could do something like:
```sql
COALESCE(tags->'name:en', '') as name
```
to only use english names and nothing else, but be aware that there probably are a lot of entries in the database that have a `name` but not an `name:en` even if `name` is in english.

**Comment by amenk** [comment]
@Ilyagurm did you succeed with this approach?

**Comment by singhyadvendra** [comment]
I am still working on this

**Comment by singhyadvendra** [comment]
multi language server is working now

**Comment by tomercagan** [comment]
@Istador / @singhyadvendra - can you elaborate on the process of getting this to work? Can I just edit the file on the running container? Should it be edited beforehand and mounted into the container? Is there some procedure how the apply the changes? A restart maybe?

Thanks!

**Comment by Istador** [comment]
> @Istador / @singhyadvendra - can you elaborate on the process of getting this to work? Can I just edit the file on the running container? Should it be edited beforehand and mounted into the container? Is there some procedure how the apply the changes? A restart maybe?
> 
> Thanks!

The modified `project.mml` file needs to be compiled to `mapnik.xml` like here:
https://github.com/Overv/openstreetmap-tile-server/blob/9679b29b509d382f14d275e6d2c16d8d02a30daa/Dockerfile#L134

Alternatively you could only modify the `mapnik.xml` manually, because the image isn't using the `project.mml` in any way anymore after building the `mapnik.xml`. (Careful, this might bite you later, see https://github.com/Overv/openstreetmap-tile-server/issues/45#issuecomment-687463676).

Yes, if you want your changes to persist, you should keep the file/files outside of the container and mount them.

Afaik, changing the xml file does require a restart for the changes to take effect. Also, tiles that were rendered before with the old version still show the old version, so they must be expired, deleted or re-rendered.

**Comment by bit-designer** [comment]
@Istador

**Comment by bit-designer** [comment]
@Istador Can you share how exactly I could recompile mapnik? Can I just run `project.mml > mapnik` in the container?

In other words, would the following to work?

`docker exec -it <Container Name or ID> /home/renderer/src/openstreetmap-carto/project.mml > /home/renderer/src/openstreetmap-carto/mapnik.xml`

Thanks!

**Comment by Istador** [comment]
> `docker exec -it <Container Name or ID> /home/renderer/src/openstreetmap-carto/project.mml > /home/renderer/src/openstreetmap-carto/mapnik.xml`

That command is missing the actual `carto` program to execute. More something like that:
```
docker exec -it <Container Name or ID> carto /home/renderer/src/openstreetmap-carto/project.mml > /home/renderer/src/openstreetmap-carto/mapnik.xml
```

But likely in quotes or something, Not that it tries to do the piping on the host.

Likely it's easier to just open an interactive shell, navigate to the directory and call the command, than doing everything in one command. Something like this:
```
docker exec -it <Container Name or ID> /bin/sh
cd /home/renderer/src/openstreetmap-carto/
carto project.mml > mapnik.xml
```

**Comment by bit-designer** [comment]
That makes sense. Thank you @Istador. I'll give that a shot!

**Comment by bit-designer** [comment]
@Dexolite, thank you for sending that!  That made it really easy to compare. Mine with yours and they were pretty much had the same (I think my copy of yours had new line characters on lines 32717 and 32718, which shouldn't matter). I tested both yours and mine, but I am still not seeing English labels. My re-run steps have simply been to replace the Mapnik file (ensuring the proper ownership and permissions), and then to force re-render the tiles of interest.

Is there some other way to re-run? If I re-start the container then the Mapnik file change will be lost, right?

Also, were you seeing the SQL exceptions in the Docker container logs? Or somewhere else?

Thanks again. You've been super kind to help.

**Comment by Dexolite** [comment]
@bit-designer , Well, in k8s, you can mount the mapnik as a volume/configmap. In docker, mount it as volume. If you prerendered, delete /var/lib/mod_tile/ajt/*
Or you can modify the Dockerfile, but you need this before "./run.sh run" is executed.

**Comment by bit-designer** [comment]
@Dexolite,

I've tried several things to get the mapnik.xml updated and to get the tile server to use it.

My most recent attempt was to copy mapnik.xml into the container from the Dockerfile prior to creating the tile server:

**Original**
```sh
FROM compiler-common AS compiler-stylesheet
RUN apt-get install -y --no-install-recommends \
 npm
RUN cd ~ \
&& git clone --single-branch --branch v5.3.1 https://github.com/gravitystorm/openstreetmap-carto.git --depth 1 \
&& cd openstreetmap-carto \
&& sed -ie 's#https:\/\/naciscdn.org\/naturalearth\/110m\/cultural\/ne_110m_admin_0_boundary_lines_land.zip#https:\/\/naturalearth.s3.amazonaws.com\/110m_cultural\/ne_110m_admin_0_boundary_lines_land.zip#g' external-data.yml \
&& npm install -g carto@0.18.2 \
&& carto project.mml > mapnik.xml
```
**Edited**
```sh
FROM compiler-common AS compiler-stylesheet
RUN apt-get install -y --no-install-recommends \
 npm
RUN cd ~ \
&& git clone --single-branch --branch v5.3.1 https://github.com/gravitystorm/openstreetmap-carto.git --depth 1 \
&& cd openstreetmap-carto \
&& sed -ie 's#https:\/\/naciscdn.org\/naturalearth\/110m\/cultural\/ne_110m_admin_0_boundary_lines_land.zip#https:\/\/naturalearth.s3.amazonaws.com\/110m_cultural\/ne_110m_admin_0_boundary_lines_land.zip#g' external-data.yml \
&& npm install -g carto@0.18.2 \
&& carto project.mml > mapnik.xml \
&& rm -rf mapnik.xml
COPY ../mapnik.xml /home/renderer/openstreetmap-carto/mapnik.xml
COPY ../mapnik.xml /home/renderer/openstreetmap-carto/
COPY ../mapnik.xml /home/renderer/
COPY ../mapnik.xml /home/
COPY ../mapnik.xml /
```

After completing the edits, I created the server (imported the .pbf and .poly files and ran the container). The server works fine, but still no English renderings (looking Israel. downloaded from Geofabrik). I also was careful to delete the rendered tiles at `/var/lib/mod_tile/ajt/*` each time. 

As you can see, I attempted to copy the mapnik file to several different paths. Several of these tests were run one-at-a-time, I just listed them all together for brevity. Again, for each case, I edited the Dockerfile and then created the server from scratch. Once running, I checked for the file in the targeted paths, but only found the original mapnik.xml file in the original location. The host path to my updated file is ../mapnik.xml.


Do you have any recommendations for me? Apparently I am not understanding something about the Docker COPY command, although I attempted to follow examples and the documentation.

Alternatively, would you be willing to elaborate on the steps to mount Mapnik as a volume. That solution path is very unclear to me because Mapnik is already built-into the container. Would I remove it from the container and then install it separately? I don't have the slightest idea of what steps to take for that recommended approach.

Thanks so much. You've been a huge help!

**Comment by Istador** [comment]
You added the `COPY` commands to the `compiler-stylesheet` stage in the `Dockerfile`.

The relative `WORKDIR` that this stage is operating in is `/root/` as can be seen here (because the `root` user is running these commands, and that is his home directory):
https://github.com/Overv/openstreetmap-tile-server/blob/705237446adacea44302692c8dfb0405dbfb2abd/Dockerfile#L204-L205

So, the absolute path of the `mapnik.xml` in that stage would be `/root/openstreetmap-carto/mapnik.xml`.
```Dockerfile
COPY  ../mapnik.xml  /root/openstreetmap-carto/mapnik.xml
# or relative:
COPY  ../mapnik.xml  ./openstreetmap-carto/mapnik.xml
```

In the `final` stage the path would be `/home/renderer/src/openstreetmap-carto/mapnik.xml` and not `/home/renderer/openstreetmap-carto/mapnik.xml`.

**Comment by bit-designer** [comment]
@Istador, thank you for correcting me.

I attempted the following Dockerfile edits:

```sh
     77 FROM compiler-common AS compiler-stylesheet
     78 RUN apt-get install -y --no-install-recommends \
     79  npm
     80 RUN cd ~ \
     81 && git clone --single-branch --branch v5.3.1 https://github.com/gravitystorm/openstreetmap-carto.git --depth 1 \
     82 && cd openstreetmap-carto \
     83 && sed -ie 's#https:\/\/naciscdn.org\/naturalearth\/110m\/cultural\/ne_110m_admin_0_boundary_lines_land.zip#https:\/\/naturalearth.s3.amazonaws.com\/110m_cultural\/ne_110m_admin_0_boundary_lines_land.zip#g' external-data.yml         \
     84 && npm install -g carto@0.18.2 \
     85 && carto project.mml > mapnik.xml
     86 COPY ../mapnik.xml /root/openstreetmap-carto/mapnik111.xml
     87 COPY ../mapnik.xml ./openstreetmap-carto/mapnik222.xml
     88 COPY ../mapnik.xml ./mapnik333.xml
```

```sh
    213 # Modify Mapnik to use English labels
    214 COPY ../mapnik.xml /home/renderer/src/openstreetmap-carto/mapnik.xml
```

The result is again the same. None of these files are present in the container after deleting the old containers/images and creating a new tile server.

I am super confused as to why I am not getting files in the container. Any additional ideas would be appreciated.

Thanks much

**Comment by Istador** [comment]
Because you try to copy from a parent directory (`COPY ../mapnik.xml [..]`), what is your docker build command look like?

You probably need to do something like `docker  build  -f subdir/Dockerfile  .` in the parent directory in order for `..` to work correctly. Otherwise the file in the parent directory isn't added to the docker build context, if you do the build in the sub directory.

Personally I'd rather do my own separate `Dockerfile` to extend the image instead of modifying the given one:
```Dockerfile
FROM  overv/openstreetmap-tile-server:v1.8.1
COPY  ./mapnik.xml  /home/renderer/src/openstreetmap-carto/mapnik.xml
```

**Comment by bit-designer** [comment]
@Istador, you're right! I hadn't realized the build issue.

As a test, I just moved the mapnik.xml into the local folder and removed the `../` from my mapnik.xml paths:

```sh
     86 COPY mapnik.xml /root/openstreetmap-carto/mapnik111.xml
     87 COPY mapnik.xml ./openstreetmap-carto/mapnik222.xml
     88 COPY mapnik.xml ./mapnik333.xml
```

After doing so, I deleted my existing containers and images and re-ran `import` and `run` inside the same project folder.

The result: I still don't see the mapnik.xml<#> files in the newly-created container.

I assume that after building the project the image is updated, right?

I am clueless as to what I am missing!

Thanks for your patience!

**Comment by Istador** [comment]
> I assume that after building the project the image is updated, right?

Depends on what you're doing exactly.

If you only do `docker  build  .` then that's clearly failing, as it'll not tag the newly build image the way you're using it, but only gives you a random hash for that image. You'll want to tag it the way you want to use it. E.g. with `docker  build  -t myimage  .` and then use `myimage` with your `docker run` commands. You could even tag it as `docker  build  -t overv/openstreetmap-tile-server  .` which'd overwrite the `latest` tag on your local machine with your image (I'd advice against doing this or at least give it a custom tag).

Likewise, if you already got a container created with the old image, you'd need to create a new one with the new image. If you only use `docker stop` and `docker start` you're still working with the old container and need to call `docker run` to create a new one.

If you're using `docker-compose`, after calling `docker-compose  build` (or `docker build` with the right tag) you'd need to update the service as well to use the newly build image (`docker-compose  up  -d`) or else it'll continue to use the old container.

**Comment by bit-designer** [comment]
@Istador,

Thanks for the response. For some reason it wasn't seeing the local image and kept pulling one from the cloud. To mitigate the issue, I simply renamed the image using the DOCKER_IMAGE variable at the top of the Makefile and then re-ran `make`. That did the trick.

I was careful to remove old docker containers and images between tests.

Thank you once again.

**Comment by bit-designer** [comment]
Update:

My English (primary label) / native (secondary label) tile server is now working! Big thanks to @Istador and @Dexolite!

**Comment by YosefCohen877** [comment]
> ```dockerfile
> ./mapnik.xml 
> ```

@finisher0 can you help me?
i want to do the same

**Comment by singhyadvendra** [comment]
[mapnik-en.xml.txt](https://github.com/Overv/openstreetmap-tile-server/files/15127153/mapnik-en.xml.txt)
create mapnik-en.xml refer attached xml
just rename it to mapnik-en.xml from mapnik-en.xml.txt. I added txt as github did not allow me to attach 

update rendered.conf to include en style like below. 
```
[styleen]
URI=/en/
TILEDIR=/var/lib/mod_tile
XML=/home/renderer/src/openstreetmap-carto/mapnik_en.xml
HOST=localhost
TILESIZE=256
MAXZOOM=20
```

**Comment by Roman587** [comment]
> [mapnik-en.xml.txt](https://github.com/Overv/openstreetmap-tile-server/files/15127153/mapnik-en.xml.txt) create mapnik-en.xml refer attached xml just rename it to mapnik-en.xml from mapnik-en.xml.txt. I added txt as github did not allow me to attach
> 
> update rendered.conf to include en style like below.
> 
> ```
> [styleen]
> URI=/en/
> TILEDIR=/var/lib/mod_tile
> XML=/home/renderer/src/openstreetmap-carto/mapnik_en.xml
> HOST=localhost
> TILESIZE=256
> MAXZOOM=20
> ```

I'm sorry, but where is the rendering file located?

**Comment by Roman587** [comment]
I'm sorry, but where is the rendering file located?

**Comment by YosefCohen877** [comment]
I don’t remember..
What do you need?

**Comment by Roman587** [comment]
@YosefCohen877 sorry, i wanna have english and native labels, but i don't understand how update rendered.conf
or maybe you can say how i can do it step by step like @finisher0

**Comment by Roman587** [comment]
@finisher0 sorry, give me please step by step guide to do like you? thank you

**Comment by Roman587** [comment]
> [mapnik-en.xml.txt](https://github.com/Overv/openstreetmap-tile-server/files/15127153/mapnik-en.xml.txt) create mapnik-en.xml refer attached xml just rename it to mapnik-en.xml from mapnik-en.xml.txt. I added txt as github did not allow me to attach
> 
> update rendered.conf to include en style like below.
> 
> ```
> [styleen]
> URI=/en/
> TILEDIR=/var/lib/mod_tile
> XML=/home/renderer/src/openstreetmap-carto/mapnik_en.xml
> HOST=localhost
> TILESIZE=256
> MAXZOOM=20
> ```

@singhyadvendra it's didn't work for me( I'm update etc/renderd.conf, is it write?

**Comment by singhyadvendra** [comment]
> > [mapnik-en.xml.txt](https://github.com/Overv/openstreetmap-tile-server/files/15127153/mapnik-en.xml.txt) create mapnik-en.xml refer attached xml just rename it to mapnik-en.xml from mapnik-en.xml.txt. I added txt as github did not allow me to attach
> > update rendered.conf to include en style like below.
> > ```
> > [styleen]
> > URI=/en/
> > TILEDIR=/var/lib/mod_tile
> > XML=/home/renderer/src/openstreetmap-carto/mapnik_en.xml
> > HOST=localhost
> > TILESIZE=256
> > MAXZOOM=20
> > ```
> 
> @singhyadvendra it's didn't work for me( I'm update etc/renderd.conf, is it write?

Hi @Roman587 , it was way back but I made small change in original xml
like below
`name` replaced with `COALESCE(tags->'name:en', name) AS name` to fetch english names
also tiles will be rendered with `/en/` in `URL`

**Comment by idanmiara** [comment]
Hi All,

Thanks for the useful pointers.

I would like to point out that the proposed solution of @YosefCohen877, to override the native name label with a name label with a cascade of languages per availability for each element (in his example `he`>`en`>`native`) works very well, also with the recent version of the service. I would suggest to add the instructions to the readme file.
https://github.com/Overv/openstreetmap-tile-server/issues/406#issuecomment-2048125728

I also looked up the instructions above by @finisher0 and others, to display a primary and a secondary labels in chosen languages (i.e. English + Native, English+<Your favorite language>)
https://github.com/Overv/openstreetmap-tile-server/issues/24#issuecomment-966704659
It looks like the instructions detailed in the comments above might get outdated as it seems like edited source files ([mapnik-en.xml) were provided and suggesting cloning specific branches of `openstreetmap-carto`. It would be very useful if detailed instructions would be added to the readme as well.
