### ISSUE TITLE
Handle Style Changes

### ISSUE THREAD

**Issue by galewis2** [Overv/openstreetmap-tile-server#249]
@tommasodelorenzo

I would bother you with an additional quick question: if I make a small change to my style, is there a simple way to apply those changes without re-running the `import`?
The fact is that when running the `import` I get errors such as 
```
+ sudo -u postgres createuser renderer
createuser: error: creation of new role failed: ERROR:  role "renderer" already exists
```
So I have to remove all data and re-run the `import`. This takes a lot of time.

_Originally posted by @tommasodelorenzo in https://github.com/Overv/openstreetmap-tile-server/issues/243#issuecomment-1046696724_

**Comment by galewis2** [comment]
So the summary is it's complicated. Did you modify the "lua" script? If so, that would require a re-import.

Otherwise, you don't need to re-run `import`, as you can just run `run`

**Comment by tommasodelorenzo** [comment]
I slightly modified the style/style.mss file for a quick example, but just stopping the container and re-running it does not implement the change. 

    Il lunedì 21 febbraio 2022, 14:00:38 CET, galewis2 ***@***.***> ha scritto:  
 
 


So the summary is it's complicated. Did you modify the "lua" script? If so, that would require a re-import.

Otherwise, you don't need to re-run import, as you can just run run

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tommasodelorenzo** [comment]
That worked. Thanks
    Il martedì 22 febbraio 2022, 19:03:55 CET, galewis2 ***@***.***> ha scritto:  
 
 


If you are using my branch, I would delete mapnik.xml in the mounted directory. https://github.com/Overv/openstreetmap-tile-server/blob/d34e0d66093ae8ff6abf2615e3e1872031cb3f55/run.sh That should trigger the re-build of mapnik.xml

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
