### ISSUE TITLE
ERROR: role "renderer" does not exist on 1.8.2

### ISSUE THREAD

**Issue by KevinBTech** [Overv/openstreetmap-tile-server#259]
Hello,

I have the same error when using those on the latest version :
`docker run -v ‪C://Repo//alsace-latest.osm.pbf:/data.osm.pbf -v map-data:/var/lib/postgresql/14/main overv/openstreetmap-tile-server import`
then
`docker run -p 8111:80 -v openstreetmap-data:/var/lib/postgresql/14/main -d overv/openstreetmap-tile-server run`. 

It is the same as #131.

**Comment by Istador** [comment]
In the commands you posted, you're using two different volumes for the database:
- import: `-v map-data:/var/lib/postgresql/14/main`
- run: `-v openstreetmap-data:/var/lib/postgresql/14/main`

Likely the `openstreetmap-data` volume you use for `run` is empty and doesn't contain the database that you imported into the `map-data` volume. Hence the error.

**Comment by Istador** [comment]
There is no version `1.8.4`. The last [tagged](https://hub.docker.com/r/overv/openstreetmap-tile-server/tags) version is [`1.8.2`](https://github.com/Overv/openstreetmap-tile-server/tree/v1.8.2) and it is not identical to the version you see here on Github.

Please consult this old documentation for the time being:
- https://hub.docker.com/r/overv/openstreetmap-tile-server
- Specifically, the `latest` version still uses postgres `12` and not `14`, meaning that you should mount the volume on `/var/lib/postgresql/12/main` instead. This was changed in pull request #248 but hasn't made its way into `latest` yet.

You are using the `latest` tag, because you don't specify a version after the `overv/openstreetmap-tile-server` in your commands (e.g. `overv/openstreetmap-tile-server:v1.8.2`). Which version that is exactly depends on when you pulled that version onto your computer. It will also not automatically update in the future, unless you tell it to do so (e.g. with the `--pull` parameter or a separate `docker pull overv/openstreetmap-tile-server` command).

**Comment by KevinBTech** [comment]
Sorry for the version number error !

> In the commands you posted, you're using two different volumes for the database:
> 
> * import: `-v map-data:/var/lib/postgresql/14/main`
> * run: `-v openstreetmap-data:/var/lib/postgresql/14/main`
> 
> Likely the `openstreetmap-data` volume you use for `run` is empty and doesn't contain the database that you imported into the `map-data` volume. Hence the error.

Yes, it's a copy mistake. 
In fact, I also tried https://stackoverflow.com/questions/61468219/issue-creating-osm-tile-server-using-docker and it was not working.

I tried
`docker run -v ‪C://Repo//alsace-latest.osm.pbf:/data.osm.pbf -v openstreetmap-data:/var/lib/postgresql/14/main overv/openstreetmap-tile-server import
`docker run -p 8111:80 -v openstreetmap-data:/var/lib/postgresql/14/main -d overv/openstreetmap-tile-server run`

then I delete the previous volume and chose a new name as shown below 
`docker run -v ‪C://Repo//alsace-latest.osm.pbf:/data.osm.pbf -v map-data:/var/lib/postgresql/14/main overv/openstreetmap-tile-server import
`docker run -p 8111:80 -v map-data:/var/lib/postgresql/14/main -d overv/openstreetmap-tile-server run`

Same error as well.

**Comment by Istador** [comment]
You're still missing the main point of my second comment:

> Specifically, the `latest` version still uses postgres `12` and not `14`, meaning that you should mount the volume on `/var/lib/postgresql/12/main` instead.

---

The documentation here on Github was updated lately to postgres `14`, but the `latest` docker image out there still requires `12`.

**Comment by KevinBTech** [comment]
> You're still missing the main point of my second comment:
> 
> > Specifically, the `latest` version still uses postgres `12` and not `14`, meaning that you should mount the volume on `/var/lib/postgresql/12/main` instead.
> 
> The documentation here on Github was updated lately to postgres `14`, but the `latest` docker image out there still requires `12`.

Yes my bad, I forgot to reply on your second comments.
It is working with postgres 12 :).
Thank you !
