### ISSUE TITLE
Dealing with container registries

### ISSUE THREAD

**Issue by nielsole** [Overv/openstreetmap-tile-server#264]
Currently only `master` gets pushed to dockerhub automatically, not tags. And in the last merge even that didn't succeed:

```
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.
```

We should:
a) implement automatic pushing of tags via travis to docker hub (see https://github.com/Overv/openstreetmap-tile-server/pull/265)
b) log in to docker before interacting with registry (see https://github.com/Overv/openstreetmap-tile-server/pull/265)
c) make ghcr registry public (This can only be done by Overv)

Long-term I think it makes more sense to have the ghcr as primary place for the containers, as we then have everything in one place which will be easier for us with no access to the docker account or travis. Once we have confirmed to be happy with ghcr, we should probably add a reference to the docker hub description (This can only be done by Overv) to the new ghcr location (or this readme) so that we can eventually phase docker hub out and remove the travis code.

**Comment by nielsole** [comment]
The problem is that due to the failed travis build there is a mismatch between the mounts for the `latest` docker image and what the readme says breaking this repo.
Since I can't retrigger a build in travis, nor push to master myself, I can't fix this situation alone. :/ 
I need support from @galewis2 @dbahrdt or @Overv (Overv, if you are reading this, please make the github container registry for this repo public)
Easiest immediate fix is simply merging https://github.com/Overv/openstreetmap-tile-server/pull/265 to get travis back up

**Comment by Istador** [comment]
Alternatively to Travis-CI (isn't that a commercial paid-only service now?), the Github Action could push to Docker Hub additionally to the GHCR.

The current workflow already supports this by checking for two secrets with the name `DOCKERHUB_USERNAME` and `DOCKERHUB_PASSWORD` (see [here](https://github.com/Overv/openstreetmap-tile-server/blob/cffbd7be5b14f060c4e4d4c83f7cf0bdd55c6541/.github/workflows/build-and-test.yaml#L121), [here](https://github.com/Overv/openstreetmap-tile-server/blob/cffbd7be5b14f060c4e4d4c83f7cf0bdd55c6541/.github/workflows/build-and-test.yaml#L128) and [here](https://github.com/Overv/openstreetmap-tile-server/blob/cffbd7be5b14f060c4e4d4c83f7cf0bdd55c6541/.github/workflows/build-and-test.yaml#L142-L148)). It [deploys](https://github.com/Overv/openstreetmap-tile-server/blob/cffbd7be5b14f060c4e4d4c83f7cf0bdd55c6541/.github/workflows/build-and-test.yaml#L108-L112) on pushes to [`master` or when someone pushes a new version tag](https://github.com/Overv/openstreetmap-tile-server/blob/cffbd7be5b14f060c4e4d4c83f7cf0bdd55c6541/.github/workflows/build-and-test.yaml#L5-L8) (both can only be authorized by maintainers). Currently without these secrets it only deploys to GHCR (which is currently private by default).

But adding these secrets would require @Overv to add them in the project settings. And should only be done if he trusts the maintainers.

Because there is a potential risk to it. A maintainer could change the workflow to access the secrets and send them somewhere else (e.g. adding a job that sends the secrets via HTTP to an external server). `pull_request`s might change the workflow, but they [don't have access to secrets](https://docs.github.com/en/github-ae@latest/actions/security-guides/security-hardening-for-github-actions#accessing-secrets). There could be malicious `pull_request`s comming in, that try to change the workflow in some way to achieve this, but they would need to be approved and merged by a maintainer first before they could access any secrets.

**Comment by nielsole** [comment]
> Because there is a potential risk to it. A maintainer could change the workflow to access the secrets and send them somewhere else 

The same holds for Travis CI already, so it is not a new risk.

**Comment by Istador** [comment]
BTW: Is there a new Travis CI URL for this project?
(Migrated from `travis-ci.org` to `travis-ci.com`?)

The badge in the readme currently links to https://travis-ci.org/github/Overv/openstreetmap-tile-server which had its last attempted PR build on 2021-06-15.

[![Build Status](https://travis-ci.org/Overv/openstreetmap-tile-server.svg?branch=master)](https://travis-ci.org/Overv/openstreetmap-tile-server) [![](https://images.microbadger.com/badges/image/overv/openstreetmap-tile-server.svg)](https://microbadger.com/images/overv/openstreetmap-tile-server "openstreetmap-tile-server")

**Comment by Overv** [comment]
For another repository of mine I have a daily cronjob running on my own server that builds the latest branch and pushes it to Docker Hub. Would that be an acceptable alternative to Github Actions/Travis-CI?

**Comment by Istador** [comment]
I think that keeping `latest` up to date should be in control of the maintainers. If the cronjob on your server ever needs to be adjusted that likely will be an issue.

Despite building `latest` regulary based on the newest `master` version and with new base image versions, the ability to push and possibly update other version tags is important too.

With Github Actions [scheduled runs](https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/events-that-trigger-workflows#schedule) can be defined in the workflow yaml.
Travis CI can do that with [cronjobs](https://docs.travis-ci.com/user/cron-jobs/), but that seem to be a UI-only setting?

**Comment by Overv** [comment]
Oh I see now that you've already set up the image in GitHub's container registry. I've made it public so that it can be pulled by anyone now and we can drop Docker Hub as far as I'm concerned. If everything is set up correctly then I'll add a note to the Docker Hub page about the image having been moved.

**Comment by Istador** [comment]
> and we can drop Docker Hub as far as I'm concerned. If everything is set up correctly then I'll add a note to the Docker Hub page about the image having been moved.

I'd not advise to drop Docker Hub.
1. It is still the default everywhere (software, caching, rate limits, firewall rules, etc).
2. Having something like `ghcr.io/` in-front of the image name might scare potential users off.
3. The version on Docker Hub should be up to date. People searching on it for images (which I often do) might disregard it, simple for not having been updated recently.
4. There are probably a lot of third party resources on the web still mentioning the image on docker hub (though a guide using the old mount points with `latest` would be broken anyway).

**Comment by Overv** [comment]
As mentioned above, though, the challenge with providing an access key for Docker Hub is that it cannot be limited to just the openstreetmap-tile-server Docker repository. It was okay while I was still the only maintainer because I could keep a check on Travis CI myself, but with the new situation it's a little bit too much of a security risk.

What I could do is set up a cronjob that automatically mirrors the images pushed to the GitHub registry to the registry on Docker Hub. This mirror operation could run every hour to keep both in sync.

**Comment by Istador** [comment]
> As mentioned above, though, the challenge with providing an access key for Docker Hub is that it cannot be limited to just the openstreetmap-tile-server Docker repository. It was okay while I was still the only maintainer because I could keep a check on Travis CI myself, but with the new situation it's a little bit too much of a security risk.

That's understandable. Sadly the Docker Hub access tokens can't be limited to specific projects.

> What I could do is set up a cronjob that automatically mirrors the images pushed to the GitHub registry to the registry on Docker Hub. This mirror operation could run every hour to keep both in sync.

That sounds good to me.

Maybe while you're at it, you could download, retag and push the old images from Docker Hub to GHCR, so they are there too.

**Comment by Overv** [comment]
Alright, I'll take care of setting it up this week.

**Comment by Overv** [comment]
The image of the latest release (both `latest` and the actual tagged `version`) in the GitHub container registry are now mirrored to Docker Hub every hour. I've also mirrored all old versions (before 2.0.0) in the Docker Hub registry to the GitHub registry.
