### ISSUE TITLE
Import multiple .osm.pbf

### ISSUE THREAD

**Issue by hb9fxq** [Overv/openstreetmap-tile-server#268]
How to import multiple .osm.pbf files at once or add an additional .osm.pbf to an existing volume?

**Comment by nielsole** [comment]
never tried this, but when the container is already `run`ing (so after the initial import), you should be able to run [osm2psql](https://github.com/Overv/openstreetmap-tile-server/blob/master/run.sh#L97) repeatedly via docker exec.
Indexes are automatically updated during insert, which might make the subsequent imports slow. If you already generated tiles, you probably want to [tell mod_tile about more imports](https://github.com/Overv/openstreetmap-tile-server/blob/master/run.sh#L123)

What are the different osm.pbf? different regions?

**Comment by hb9fxq** [comment]
OK thanks. The INDEX update might be an issue, have not tried but will probably merge files manually before import like this: 

`osmium cat germany-latest.osm.pbf switzerland-latest.osm.pbf -o de-ch.osm.pbf`

**Comment by Istador** [comment]
> never tried this, but when the container is already `run`ing (so after the initial import), you should be able to run [osm2psql](https://github.com/Overv/openstreetmap-tile-server/blob/master/run.sh#L97) repeatedly via docker exec.

Running `osm2psql` this with `--create` would delete existing data from the database. It'd result in a freshly imported database. At first you might not even notice that, because the old rendered tiles are still there and aren't re-rendered immediately.

The way to add additional things to an existing database is by using `osm2psql` with `--append` instead.

But if ever possible, merging multiple `pbf` files and `import` it freshly is to be prefferred, because `--append` takes orders of magnitude longer to execute than merge and `import`.
