### ISSUE TITLE
tile-server container doesn't lose mem usage.

### ISSUE THREAD

**Issue by dongjunson** [Overv/openstreetmap-tile-server#27]
i had docker import planet.osm.pdf. (during for 7 days)
finished pre-render zoomlevel 7~14.
but docker stats is
tile-server MEM USAGE always 99.9% ( setted --memory=30G)
how do lose mem usage?
it is normal mem-usage 99%?

**Comment by gakowalski** [comment]
I do not know what the memory usage of tile server for the whole planet looks like as my server only serves tiles for only one country, but during the half-year use I noticed that PostgreSQL behaves very strange with certain configurations of threads and memory limits. If you have this possibility, try to build and run [my modification of this container](https://github.com/pot-gov-pl/openstreetmap-tile-server/tree/master) in which [PostgreSQL is configured with settings suggested for tile servers](https://github.com/pot-gov-pl/openstreetmap-tile-server/blob/poland/postgresql.custom.conf). Also, try to run the container with different prameters values for threads, allocated memory, and [shared memory](https://github.com/pot-gov-pl/openstreetmap-tile-server/issues/3#issuecomment-474410110).

**Comment by stevo01** [comment]
> i had docker import planet.osm.pdf. (during for 7 days)

Could you send me details about the used hardware (CPU, cores and hard disc, used RAM )? Do you have a logfile from import available? How big is the database image after import? I would like to take over your results to my overview with [benchmarks](https://github.com/stevo01/openstreetmap-tile-server/blob/dev-stevo/Doc/Benchmarks.md).

> it is normal mem-usage 99%?

The memory usage of software is semilar to air in a room. It takes all what is available :-)
You can use tools like htop inside container to get fast information which processes occupy how mutch memory and cpu ressources. You can find information how to attach to docker console and how to install and start htop in my [notes](https://github.com/stevo01/openstreetmap-tile-server/blob/dev-stevo/Doc/UsefulCommands.md).

**Comment by stevo01** [comment]
> finished pre-render zoomlevel 7~14.

next offtopic qestion: 
-  How to you trigger the tile server to prerender the tiles? is there a tool available?
- Can you explain the intension of pre-render tiles? I guess is it a strategy to speed up the delivery of tiles or do you need the prerendered tiles for particular use case.

**Comment by stevo01** [comment]
> * How to you trigger the tile server to prerender the tiles? is there a tool available?

Ok I revoke my question. I found the answer here: https://github.com/Overv/openstreetmap-tile-server/issues/17

**Comment by Istador** [comment]
>     * Can you explain the intension of pre-render tiles? I guess is it a strategy to speed up the delivery of tiles or do you need the prerendered tiles for particular use case.

Usually you want to pre-render the tiles to reduce the response time the web-clients have to wait to retrieve the tiles to offer a fluid map navigation. Because if a tile (image file) doesn't already exist on the tile server, it needs to be rendered and saved to disk which takes time.

Especially for lower zoom levels (0-10) where rendering takes a bit longer, or when you expect a lot of requests at once (like when switching from google maps to osm in an already existing application with a large user base) it makes sense to pre-render.

Knowing which zoom levels your application is using by default helps to decide what zoom levels to pre-render.
Rendering higher zoom levels worldwide takes up a lot of disk space and rendering time (it doesn't make much sense to pre-render zoom levels 16-18 in the middle of nowhere like in the ocean).
Knowing the points of interest of your application can help you to decide where to pre-render (e.g. zoom-level up to 18 for 5km around your POI).

**Comment by dongjunson** [comment]
• zoomlevel 8 64,896 tilea / 7769.92 s 
	• zoomlevel 9 262,016 tiles / 4671.35 s
	• zoomlevel 10 488,704 tiles / 1742.20 s
	• zoomlevel 11 4,193,856 tiles / 7219.89 s
	• zoomlevel 12 16,776,192 tiles / 298084.0 s
zoomlevel 13  67,106,368 tiles / 1093291.1 s

**Comment by stevo01** [comment]
> i had docker import planet.osm.pdf. (during for 7 days)
> finished pre-render zoomlevel 7~14.
> but docker stats is
> tile-server MEM USAGE always 99.9% ( setted --memory=30G)
> how do lose mem usage?
> it is normal mem-usage 99%?

I can reproduce the described behavier now. I started the pre render procedure with command "render_list -a -m ajt -z 6 -Z 6 -l 800 -n 12" yesterday. Today I observed that my workstation is verry slow and analysis shows that process renderd consumes 92GB (workstation includes 64GByte RAM and 64GByte SWAP disk). I think the behavior is not normal because the prerender process is finished and renderd should free the not needed memory. 

I found following issue "[memory consumption #181](https://github.com/openstreetmap/mod_tile/issues/181)" which reports semilar observations.
