### ISSUE TITLE
typo in docker hub documentation in "setting up server", container data path

### ISSUE THREAD

**Issue by MirRahim** [Overv/openstreetmap-tile-server#274]
Hi,
```
docker run \
    -v /absolute/path/to/luxembourg.osm.pbf:/data.osm.pbf \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import
```
 in the above command, the path to data inside the container should be changed from:

`-v /absolute/path/to/luxembourg.osm.pbf:/data.osm.pbf `

to

`-v /absolute/path/to/luxembourg.osm.pbf:/data/region.osm.pbf `

regards,

**Comment by Istador** [comment]
That's not the only issue.
For example it's `/data/database/` now instead of `/var/lib/postgresql/12/main` or `/var/lib/postgresql/14/main`.

The docker hub overview is out of sync with the [README.md](https://github.com/Overv/openstreetmap-tile-server/blob/cffbd7be5b14f060c4e4d4c83f7cf0bdd55c6541/README.md) in this repository.
Does the overview need to be updated manually by @Overv ?

**Comment by Overv** [comment]
Right now, yes, but it looks like there is an API to update the description. I'll try to extend the cronjob this week to also automatically update the description to the latest `README.md`.

**Comment by Overv** [comment]
The Docker Hub description should now automatically sync to the README in the `master` branch every hour.
