### ISSUE TITLE
Password for postgres user? 

### ISSUE THREAD

**Issue by MKvasco** [Overv/openstreetmap-tile-server#275]
I know this is not really issue for everybody but for me it is, I want to create another database within postgre, but renderer does not have privileges and I cant guess the password. You do not mention it in your docs, I am making map application where I need to store another data from users. I would not be happy to run another docker postgre just because of this (cost of performance)

**Comment by Istador** [comment]
https://github.com/Overv/openstreetmap-tile-server/blob/5572c9722ef7cc478d0143436b9f723c54171527/run.sh#L11-L13

There's a `PGPASSWORD` environment variable to configure this. The default password of user `renderer` is `renderer`

**Comment by MKvasco** [comment]
Yes, I know that default password for renderer is renderer, but I need to access postgres user to create new database

**Comment by nielsole** [comment]
```
$ docker exec -it $CONTAINER_NAME bash
root@98959f1df078:/# su postgres
postgres@98959f1df078:/$ psql
psql (12.9 (Ubuntu 12.9-0ubuntu0.20.04.1))
Type "help" for help.

postgres=# 
```

**Comment by Istador** [comment]
Afaik the `postgres` database user doesn't have a password by default. Or if there is one for internal technical reasons, it's not set up in a way that you can access that password in any way. Authentication to it is guarded by the `postgres` unix user. And afaik that user doesn't have a password either. You need to be `root` in order to impersonate `postgres` to gain access to the database user `postgres`.

**Comment by nielsole** [comment]
you can also create separate users, databases and passwords when you are the `postgres` users. But this is out of scope for this repo.

**Comment by MKvasco** [comment]
Yes sorry I didnt update you, I solved it already thanks
