### ISSUE TITLE
Access a location upfront using URL

### ISSUE THREAD

**Issue by asitemade4u** [Overv/openstreetmap-tile-server#278]
I just installed the OSM Tile Server and love it!
Is there a way to access a specific location upfront, through the URL -- just like OSM does with URLs, eg. `https://www.openstreetmap.org/#map=14/40.7438/-73.9425`
I tried to do the same with your server and it did not work.
Would also be great for bookmarking.

Best,
Stephen

**Comment by Istador** [comment]
The [leaflet-demo.html](https://github.com/Overv/openstreetmap-tile-server/blob/master/leaflet-demo.html) that is saved under `/var/www/html/index.html` and is provided when GETting `/` is only an example on how to use the tile server. E.g. a quick check to see if it works.

---

For a feature like you suggested you'd need to write your own code.

Instead of this:
https://github.com/Overv/openstreetmap-tile-server/blob/5572c9722ef7cc478d0143436b9f723c54171527/leaflet-demo.html#L26

You'd need to parse the `window.location.hash` and provide the right values to the `setView` method.

There are also libraries that offer this functionality:
- https://github.com/mlevans/leaflet-hash
- https://github.com/gregrobson/leaflet-hash-plus

**Comment by nielsole** [comment]
We have unfortunately decided to not merge the above PR, to avoid scope creep. This this will not be implemented in this repo any time soon
