### ISSUE TITLE
Pre-tiling

### ISSUE THREAD

**Issue by rmoggia** [Overv/openstreetmap-tile-server#285]
Hi. What is the best way to get pre-tiling?
I was thinking of opening a shell in the docker and running the render_list command as like:
render_list -m default -a -z 0 -Z 19 --num-threads=10
Thanks

**Comment by Istador** [comment]
Well, rendering zoom levels 0-18 for the whole world would [approximately](http://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=-179.99,-84.99,179.99,84.99) take about 47 TB in total for the `osm-tiles` volume. I don't know how much space z19 would require, but I'd estimate about 200 TB (so about 250 TB in total).

So, that's not really a viable option.

You'll likely only want to render everything (`-a`) on lower zoom levels and higher zoom levels only in areas that have something (why would you want to pre-render zoom level 19 in the middle of the ocean?).

What might be helpful additional to `render_list` is [render_list_geo.pl](https://github.com/alx77/render_list_geo.pl), to render targeted based on bounding boxes with geocoordinates.

For example in my use case at work (from memory of a few years ago, so the numbers might be slightly wrong), I rendered the whole planet up to z10 (~2 GB), up to z14 for the geographic areas where our main business is, and up to z18 near ~3000 points of interest. Those POI are shown as an extra layer on top of the map, which are most likely to cause zoom ins by customers.

**Comment by rmoggia** [comment]
My area of ​​interest is the Italian region. I have to be honest I am not an OSM and GIS expert. I use it in an instrumental way because some of my clients want to see a street building. So I thought about pre-tiling to avoid waiting, but maybe that's not the right policy. Perhaps it is better to size a hardware that allows you to get the desired zooms faster. What do you think about it?
Thanks

**Comment by Istador** [comment]
I mean if it's only Italy, it isn't that much of an issue and becames way more managable. Because compared with all the rest of the world it's only a tiny fraction.

Pre-rendering higher zoom levels isn't even that important. Because they are so zoomed in, they don't have that much data to display per image, so even weak servers can render them rather quickly on the fly. Only lower zoom levels are important to consider, because the renderer has to query/iterate over thousands of database rows.

---

World z0-z10, Italy z11-z14, requires about 4 GB disk space (untested):

```
c=$(docker ps | grep "overv/openstreetmap-tile-server" | grep -Eo "^[0-9a-f]+")

# render all the world from z0-z10 (~2 GB)
docker exec -it "$c"  render_list  -a  -f  -m ajt  -z 0  -Z 10

# download render_list_geo.pl
docker exec -it "$c"  wget  https://raw.githubusercontent.com/alx77/render_list_geo.pl/master/render_list_geo.pl
docker exec -it "$c"  chmod  +x  render_list_geo.pl

# render italy from z11 to z14 (~2 GB)
docker exec -it "$c"  ./render_list_geo.pl  -f  -m ajt  -z 11  -Z 14  -x 6.48   -y 43.5   -X 13.95  -Y 47.16
docker exec -it "$c"  ./render_list_geo.pl  -f  -m ajt  -z 11  -Z 14  -x 8.14   -y 41.11  -X 14.42  -Y 43.6
docker exec -it "$c"  ./render_list_geo.pl  -f  -m ajt  -z 11  -Z 14  -x 13.28  -y 39.68  -X 18.78  -Y 42.14
docker exec -it "$c"  ./render_list_geo.pl  -f  -m ajt  -z 11  -Z 14  -x 15.43  -y 37.67  -X 17.47  -Y 39.76
docker exec -it "$c"  ./render_list_geo.pl  -f  -m ajt  -z 11  -Z 14  -x 11.67  -y 36.35  -X 15.78  -Y 39
docker exec -it "$c"  ./render_list_geo.pl  -f  -m ajt  -z 11  -Z 14  -x 7.75   -y 38.59  -X 10.16  -Y 41.47
docker exec -it "$c"  ./render_list_geo.pl  -f  -m ajt  -z 11  -Z 14  -x 12.05  -y 35.27  -X 13.17  -Y 36.12
```

Regions: [1](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=6.48,43.5,13.95,47.16), [2](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=8.14,41.11,14.42,43.6), [3](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=13.28,39.68,18.78,42.14), [4](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=15.43,37.67,17.47,39.76), [5](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=11.67,36.35,15.78,39), [6](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=7.75,38.59,10.16,41.47), [7](https://tools.geofabrik.de/calc/#type=geofabrik_standard&bbox=12.05,35.27,13.17,36.12)

Increasing this to z15 might take about 7 GB in total.
Increasing this to z16 might take about 18 GB in total.
Increasing this to z17 might take about 51 GB in total.
Increasing this to z18 might take about 240 GB in total.

(With z17 or z18 you should likely define more regions and be more precise, to cover less water.)

**Comment by rmoggia** [comment]
Thanks Istador. I wasn't hoping for such professional help. I am very grateful to you. You cleared a very thick fog for me. I will move according to your method.
