### ISSUE TITLE
Some tiles for some zoom levels not rendering

### ISSUE THREAD

**Issue by oldwired** [Overv/openstreetmap-tile-server#287]
I installed an run the tile server via
```
docker volume create osm-data
docker run \
    -e UPDATES=enabled \
    -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/dach-latest.osm.pbf \
    -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/dach.poly \
    -v osm-data:/data/database/ \
    overv/openstreetmap-tile-server \
    import

docker volume create osm-tiles
docker run --restart=always \
    -p 8080:80 \
    -e UPDATES=enabled \
    -v osm-data:/data/database/ \
    -v osm-tiles:/data/tiles/ \
    -e ALLOW_CORS=enabled \
    -d overv/openstreetmap-tile-server \
    run
```
but some tiles for some zoom levels don't show up:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/9700404/173204639-079d8631-7cf1-4734-841e-8298e41d2a47.png">
Or totally zoomed out I see the outlines: 
<img width="175" alt="image" src="https://user-images.githubusercontent.com/9700404/173204884-c6651369-5f21-40c0-915d-881632299ff3.png">
But when I further zoom in I just see grey
<img width="459" alt="image" src="https://user-images.githubusercontent.com/9700404/173204911-1329fe03-8429-46c8-80ea-d4f3eddd7427.png">
until I further zoom in and the tiles start to appear again.

I tried to make sense of the docker logs for the import and the run containers, but don't see any glaring errors. But the output is also a bit strange, because I see other lines scrolling by when the docker logs command runs, as when I redirect the output into less or a file...

Edit: I noticed, I missed `-v osm-tiles:/data/tiles/ \` on the import, so I restarted from scratch, but it did not change. The missing tiles produce 404 when trying to GET them.

**Comment by oldwired** [comment]
The machine has 96GB and nothing else to do.  
But it makes me wonder why it happens consistently at the same area. I deleted the container and volumes and started from scratch and it happened again at the exact same place.

Trouble is I have no idea where to look. Does the renderer log somewhere? Is there something in the DB I could check?

**Comment by Istador** [comment]
```
docker container ls --all | grep overv
docker logs ${container_id}
```

**Comment by oldwired** [comment]
I had more success with `docker attach ${container_id}` to view it live. I might have run into the shared memory problem. But in the mean time I switched to whole europe, because in the end I need a european map.

**Comment by Istador** [comment]
The logs command also has a `--follow` directive to continue watching live output, as well as a `--tail` to limit it to the last X log lines.

The thing to be aware of when using `attach` (without `--no-stdin`) is that you attach yourself to the container as if you'd `run` it without the `-d` (detatched) flag. So your keyboard inputs are send to the container, e.g. `CRTL-C` to cancel the running command.

The shared memory problem in my opinion is a general configuration problem that affects everyone. The `--shm-size` option should be part of every `docker run` command when using this image. Because afaik the postresql database is configured to use 128 MB or more of shared memory, but the docker default only assigns 64 MB to the containers.
