### ISSUE TITLE
how can i change name of location in openstreetmap-tile-server which run locally

### ISSUE THREAD

**Issue by javad2157** [Overv/openstreetmap-tile-server#324]
hello everybody
i ran openstreetmap locally on my server and use -v switch to bind host volume to docker machine.
i tried to change postgres database with pgadmin and navicat to change name of location in map but that is not apply to map however the field in database had changed.
Is there a routine that can do this?
thanks

**Comment by galewis2** [comment]
I'm not sure what you mean? What exact steps are you trying to do?

**Comment by javad2157** [comment]
> I'm not sure what you mean? What exact steps are you trying to do?

thanks for your reply
I just want to change the name of a location on the map. to do this i follow these steps:
i first run openstreetmap with below command:
![image](https://user-images.githubusercontent.com/89399278/191921200-6ac63b37-c677-45ae-a44f-2ae24c369897.png)
then i go to database and change name field in planet_osm_roads and planet_osm_line table on gis database and update database.
![image](https://user-images.githubusercontent.com/89399278/191922553-fa212cf3-3b24-406c-acab-6c5c2f2dfa58.png)
i bind a volume on the host to container and after do above steps i remove previous container and create new one with
changed database. 
the problem is the new container is unaffected by what I did.

**Comment by Istador** [comment]
Because you aren't mounting the tiles, you don't need to re-render them or call any command after your change. Creating a new container should be enough.

Please consult the [style](https://github.com/gravitystorm/openstreetmap-carto/blob/v5.4.0/project.mml) to find out what you need to change where. The `name` you want to change might be in one of the other tables (e.g. `planet_osm_polygon`,  `planet_osm_point` or `planet_osm_nodes`).

For example the `name` in `planet_osm_roads` isn't even used anywhere at all.

Regarding changing the name of a road you probably need to change each individual segment of the road.

Sometimes it helps to incpect the things on https://www.openstreetmap.org/ to figure out the right `osm_id`.

---

If it's a name correction/change that applies to everyone (e.g. the name of a street changed), which should apply to every OSM instance in the world, then that change should better be done on https://openstreetmap.org and not manually on your local server.

**Comment by javad2157** [comment]
> Because you aren't mounting the tiles, you don't need to re-render them or call any command after your change. Creating a new container should be enough.
> 
> Please consult the [style](https://github.com/gravitystorm/openstreetmap-carto/blob/v5.4.0/project.mml) to find out what you need to change where. The `name` you want to change might be in one of the other tables (e.g. `planet_osm_polygon`, `planet_osm_point` or `planet_osm_nodes`).
> 
thanks for your reply, you right. I chose the wrong table. by fixing that now i can change location name on the map.
