### ISSUE TITLE
Segmentation fault, planet import latest version 2.2.0

### ISSUE THREAD

**Issue by Kofl** [Overv/openstreetmap-tile-server#330]
Hi,

I try to import the planet, but it always ends in an segmentation fault. 
Already increased cache (-C 64000), but didnt solve the issue.
Thanks for any idea.

> map_1  | + sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-transform-script /data/style/openstreetmap-carto.lua --number-processes 24 -S /data/style/openstreetmap-carto.style /data/region.osm.pbf --flat-nodes /data/tiles/flat_nodes.bin -C 64000
> map_1  | 2022-09-29 07:16:44  osm2pgsql version 1.6.0
> map_1  | 2022-09-29 07:16:44  Database version: 14.4 (Ubuntu 14.4-0ubuntu0.22.04.1)
> map_1  | 2022-09-29 07:16:44  PostGIS version: 3.2
> map_1  | 2022-09-29 07:16:44  Setting up table 'planet_osm_point'
> map_1  | 2022-09-29 07:16:44  Setting up table 'planet_osm_line'
> map_1  | 2022-09-29 07:16:44  Setting up table 'planet_osm_polygon'
> map_1  | 2022-09-29 07:16:44  Setting up table 'planet_osm_roads'
> 2022-09-29 16:28:29  Reading input files done in 33105s (9h 11m 45s).
> map_1  | 2022-09-29 16:28:29    Processed 7922669010 nodes in 3758s (1h 2m 38s) - 2108k/s
> map_1  | 2022-09-29 16:28:29    Processed 888055760 ways in 20713s (5h 45m 13s) - 43k/s
> map_1  | 2022-09-29 16:28:29    Processed 10242152 relations in 8634s (2h 23m 54s) - 1k/s
> map_1  | 2022-09-29 16:28:29  Clustering table 'planet_osm_line' by geometry...
> map_1  | 2022-09-29 16:28:29  Clustering table 'planet_osm_roads' by geometry...
> map_1  | 2022-09-29 16:28:29  Clustering table 'planet_osm_point' by geometry...
> map_1  | 2022-09-29 16:28:29  Clustering table 'planet_osm_polygon' by geometry...
> map_1  | 2022-09-29 16:28:35  Done postprocessing on table 'planet_osm_nodes' in 0s
> map_1  | 2022-09-29 16:28:35  Building index on table 'planet_osm_rels'
> map_1  | 2022-09-29 16:28:35  Building index on table 'planet_osm_ways'
> map_1  | 2022-09-29 17:10:06  Creating geometry index on table 'planet_osm_roads'...
> map_1  | 2022-09-29 17:14:36  Creating osm_id index on table 'planet_osm_roads'...
> map_1  | 2022-09-29 17:14:49  Analyzing table 'planet_osm_roads'...
> map_1  | 2022-09-29 17:19:19  Creating geometry index on table 'planet_osm_point'...
> map_1  | 2022-09-29 18:01:59  Creating osm_id index on table 'planet_osm_point'...
> map_1  | 2022-09-29 18:05:02  Analyzing table 'planet_osm_point'...
> map_1  | /run.sh: line 130:    88 Segmentation fault      sudo -u renderer osm2pgsql -d gis --create --slim -G --hstore --tag-> > transform-script /data/style/${NAME_LUA:-openstreetmap-carto.lua} --number-processes ${THREADS:-4} -S /data/style/${NAME_STYLE:-openstreetmap-carto.style} /data/region.osm.pbf ${OSM2PGSQL_EXTRA_ARGS:-}

_docker-compose.yml_

> version: '3'
> services:
>   map:
>     image: overv/openstreetmap-tile-server:2.2.0
>     environment:
>       - THREADS=24
>         #      - UPDATES=enabled
>       - OSM2PGSQL_EXTRA_ARGS=--flat-nodes /data/tiles/flat_nodes.bin -C 64000
>     ports:
>       - "80:80"
>     volumes:
>       - /opt/osm-tiles/planet-latest.osm.pbf:/data/region.osm.pbf
>       - osm-data-sql:/data/database/
>       - osm-tiles:/data/tiles/
>       - /opt/openstreetmap-carto-modified:/data/style/
>     command: "import"
> volumes:
>     osm-data-sql:
>      external: true
>     osm-tiles:
>      external: true

**Comment by Istador** [comment]
A segmentation fault is a problem related to accessing memory incorrectly. That could have all kinds of different reasons.

---

Increasing `THREADS` or the `osm2pgsql` cache without exaclty knowing what you're doing is generally a bad idea. You basically use up to `64 GB` of memory for the `osm2pgsql` cache and with `THREADS` let the database use up to additional `45.2 GB` of memory.

```
3 + (1 + 24 threads) x 14 tables = 353 connections
353 connections x 128 MB work_mem = 45.2 GB
```

Does your system has more than `110 GB` of free memory?

Also, using `353` database connections exceeds the configured maximum value of `250` (exceeding this limit will not result in slower performance but in errors):
https://github.com/Overv/openstreetmap-tile-server/blob/10571b77b756bea8046f59de08d27f84c4faffe9/postgresql.custom.conf.tmpl#L12

- https://osm2pgsql.org/doc/manual.html#number-of-connections

---

What might also be related to memory, (but usually results in disk full errors) is the shared memory size which I highly suggest to increase, because the docker default (`64 MB`) is just too low for the default postgres setting (`128 MB`).
https://github.com/Overv/openstreetmap-tile-server#troubleshooting (with docker compose: `shm_size: 256M`)

---

Suggestions:
- lower `THREADS` to 16 or less or increase the postgres `max_connections` setting.
- lower `THREADS`, the `-C` cache or the postgres `work_mem` according to the memory that your system has.
- increase the `shm_size: 256M`.

Note: these are theoretical memory extremes, it's not guaranteed that the import really maxes out on these (though on a planet import that's likely possible). Also: there might be additional memory requirements or bottle necks from other parts of the software stack (other programs and settings) and of the host system itself, so the actual memory consumption by the import might be higher than outlined. Configure your limits conservatively - don't max out on them hoping for the best.

**Comment by Kofl** [comment]
Awesome, thanks a lot for the detailed information, really helpful. I will retry the import with your suggestions.

**Comment by Kofl** [comment]
Worked fine now, docker-compose.yml for reference
(machine has 24 cores, 120 GB memory)


> version: '3'
> services:
>   map:
>     image: overv/openstreetmap-tile-server:2.2.0
>     shm_size: 256M
>     environment:
>       - THREADS=16
>       - OSM2PGSQL_EXTRA_ARGS=--flat-nodes /data/tiles/flat_nodes.bin -C 2000
>     ports:
>       - "80:80"
>     volumes:
>       - /opt/osm-tiles/planet-latest.osm.pbf:/data/region.osm.pbf
>       - osm-data-sql:/data/database/
>       - osm-tiles:/data/tiles/
>       - /opt/openstreetmap-carto-modified:/data/style/
>     command: "import"
> volumes:
>     osm-data-sql:
>      external: true
>     osm-tiles:
>      external: true
