### ISSUE TITLE
How to overwrite a .pbf file while the server is running?

### ISSUE THREAD

**Issue by John2397** [Overv/openstreetmap-tile-server#333]
How can I overwrite an existing .pbf file with another one while the server is running? So let's say the `run` command is executed with a region A. I now want to replace region A with region B. What do I do?  One of the answers [here](https://giters.com/Overv/openstreetmap-tile-server/issues/241) says the following: 

> For updating an existing bpf, you don't need to (and shouldn't) run import a second time simply keep `run` running with UPDATES=enabled to get minutely updates (of course only work if import also was run with this flag..

So what I tried was:

Import:
```

docker run \
    -e UPDATES=enabled \
    -v /path/to/regionA.osm.pbf:/data/region.osm.pbf \
    -v /path/to/regionA.poly:/data/region.poly \
    -v osm-data:/data/database/ \
    overv/openstreetmap-tile-server \
    import
```
Run:
```
docker run \
    -p 8081:80 \
    -e REPLICATION_URL=https://planet.openstreetmap.org/replication/minute/ \
    -e ALLOW_CORS=enabled \
    -e MAX_INTERVAL_SECONDS=60 \
    -e UPDATES=enabled \
    -v osm-data:/data/database/ \
    -v osm-tiles:/data/tiles/ \
    -v /path/to/regionA.osm.pbf:/data/region.osm.pbf \
    -v /path/to/regionA.poly:/data/region.poly \
    -d overv/openstreetmap-tile-server \
    run
```
RegionA is now successully displayed on the map.

While the server is running, I now replace the content of `regionA.osm.pbf` (on host) with the content of region B. Same with the `.poly` file. Due to the `update=enabled` I expect the server to detect the changes on the `.osm` file. However, no update occurs.

**Comment by Istador** [comment]
The comment that you quote is from here: https://github.com/Overv/openstreetmap-tile-server/issues/241#issuecomment-1079301362
IDK why you'd use an external third party website that scrapes the content from GitHub to enrich it with advertisements to make money out of it instead of using GitHub directly...

---

If I understand your problem correctly, then that comment doesn't apply to your situation.
What it talks about is UPDATING a region (so, the same region, but with newer data), not replacing it with another region.

If you want your region to keep up to date and always represent the latest changes from openstreetmap.org, then you provide a `.poly` file during your initial import and set `UPDATES=enabled`. This will automatically download the changes, apply it to the database, and re-renders tiles.

If you want to switch to another region, e.g. from `USA` to `Canada`, then you have to import again. The easiest solution to that would be to throw away everything and create the containers and volumes from scratch.

If you want to feature multiple regions, e.g. `USA` AND `Canada`, you'll either need to `import` the second region in `append` mode after the first import (<-- not recommended!), or merge both `.pbf` and both `.poly` files together and import them together in one step.

---

Also:
The volume mounts for `/data/region.osm.pbf` and `/data/region.poly` are only used and needed for the `import`. The `run` command isn't using them at all.
