### ISSUE TITLE
Is it possible to find online the osm-data volume tar files?

### ISSUE THREAD

**Issue by John2397** [Overv/openstreetmap-tile-server#335]
Sorry if this is a stupid question, but, as per documentation: 

> if you want to run the openstreetmap-tile server on a computer that is isolated, you must first import on an internet connected computer, export the osm-data volume as a tarfile, and then restore the data volume on the target computer system.

That means, once the `import` process is finished, the final `osm-data` volume tar file can be used at any other computer and the `run` command can be executed right away.
If this is the case, are there somewhere online the already built `osm-data` volume tar files, for any regions, so the  `import` process can be skipped?

**Comment by Istador** [comment]
Afaik this doesn't exist.

It also doesn't make too much sense to do it:
- The imported disk space required for the imported database instead of the `.pbf` files is way bigger (older example: 21 GB `.pbf` => 400 GB imported database, though with compression this could likely go down a lot).
- The import into the database is specific to the style used ([osm-carto](https://github.com/gravitystorm/openstreetmap-carto)). Using another map style or even another version (currently: [v5.4.0](https://github.com/gravitystorm/openstreetmap-carto/tree/v5.4.0)) of the same style would likely require separate imports.
- It would be specific for the postgres database version used (currently `postgresql` 14, but in the past versions 12 and 10 were also in use by this image).
- The `/data/database/` folder contains some additional persistent files (flatnodes, automatic update files) that might be specific to the image version in use.

Maintaining imported versions for all the different regions (and possible region combinations!), styles, style versions, database versions and image versions would just cost too much effort and disk space.

**Comment by John2397** [comment]
That makes sense! Thank you!
