### ISSUE TITLE
Low CPU-utilization when importing? | What is actual bottleneck?

### ISSUE THREAD

**Issue by TheSwede86** [Overv/openstreetmap-tile-server#339]
Hello,

I've been importing the entire "Europe"-map from 26/10 ~ 15:40 so it has been running in excess of 4 days (time when writing this is 30/10 ~ 19:00).

My specs are:
i5-8600K (6 cores / 6 threads)
16GB RAM
Writing to an external USB 3,0 device since my internal HDD doesn't have enough space (currently my external drive has a 500GB Ext4-partition which is dedicated to this and it has filled 231GB (~ 54% full).
Ubuntu 22.04.1 is my host and it is installed on my NVME SSD.

However when checking "System Monitor" I can see that the CPU-utilization is really low across all cores.
I know I should have specified:
`-e THREADS=6`
and
`-e "OSM2PGSQL_EXTRA_ARGS=-C 16384" \`
before running the "import"-command but I still think it is weird that I see such a low utilization across all cores unless the actual bottleneck is throughput for my external HDD?

![Screenshot from 2022-10-30 19-00-47](https://user-images.githubusercontent.com/11052009/198894904-43e6cbec-78c2-463e-a69b-2b7d24494cd0.png)

Best Regards - Karl

**Comment by Istador** [comment]
The bottleneck is definitely the HDD. The import basically is just copying data arround, from the pbf file (on SSD? or also HDD?) into the postgres database (HDD).

As far as I'm aware there isn't much complex computation involved, but only very basic decisions (is it in the region we want to import, does this has a type that should be imported, in which table does it go, does it already exist in the table, etc.).
But even if it were very CPU-intensive computions, because to the slowness of HDDs, it'd likely still need to wait for the HDD most of the time.

Increasing the cache/memory and using flat-nodes should help a lot when importing to a HDD (instead of to an SSD/NVMe).

**Comment by TheSwede86** [comment]
> The bottleneck is definitely the HDD. The import basically is just copying data arround, from the pbf file (on SSD? or also HDD?) into the postgres database (HDD).
> 
> As far as I'm aware there isn't much complex computation involved, but only very basic decisions (~is it in the region we want to import~, does this has a type that should be imported, in which table does it go, does it already exist in the table, etc.).
> But even if it were very CPU-intensive computions, because to the slowness of HDDs, it'd likely still need to wait for the HDD most of the time.
> 
> Increasing the cache/memory and using flat-nodes should help a lot when importing to a HDD (instead of to an SSD/NVMe).

Thanks for your reply.

Freed space on my SSD (NVMe) and set the threads and cache/memory to higher values then the defaults.

Seeing speeds around 500k/s rather then 120k/s.
