### ISSUE TITLE
Adding more countries error: createuser creation of new role failed: ERROR:  role "renderer" already exists

### ISSUE THREAD

**Issue by ahmedkhelifi** [Overv/openstreetmap-tile-server#342]
I have followed the steps and successfully host the map of Luxembourg. Now I'm trying to add Germany as well, so I tried to downloading as following:

`    docker run \
    -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/germany-latest.osm.pbf \
    -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/germany.poly \
    -v osm-data:/data/database/ \
    overv/openstreetmap-tile-server \
    import
`

This gives me the following error:

```
listen_addresses = '*'
autovacuum = on
+ service postgresql start
 * Starting PostgreSQL 14 database server
   ...done.
+ sudo -u postgres createuser renderer
```
```
createuser: error: creation of new role failed: ERROR:  role "renderer" already exists

```

I assume the role renderer was already set when I downloaded the first map, so no need to recreate it when adding another map to an already existing data set. I'm not (yet) familiar with docker or osm, any help how do I bypass creating the same role again or how do I download Germany and add it to the dataset?

Thanks:)

**Comment by Istador** [comment]
The `import` is a one time operation.

Even if we'd fix this error, so that it proceeds with the import, it'd not do what you want. Meaning it would not add Germany to the database additionally to the already imported Luxembourg, but it would import Germany and thereby removing Luxembourg.

The underlying `osm2pgsql` command does have an alternative command to `import` called `append`, but I'd only suggest to use it for differential updates, and NOT to add additional regions, because it is orders of magnitudes slower than the import.

The recomended way to import multiple regions, is by first merging the `.osm.pbf` (and `.poly`) files together, and then `import` the merged regions together with one command.

**Comment by ahmedkhelifi** [comment]
alright, good to know. Thanks for the quick reply!

**Comment by Manoj-py** [comment]
PBF error: invalid BlobHeader size (> max_blob_header_size). Got this error while using mereged.osm..pbf file of 2 countries
