### ISSUE TITLE
Tile status - pending

### ISSUE THREAD

**Issue by hajcik1** [Overv/openstreetmap-tile-server#358]
Hello. On every zoom level, status of tiles are pending for 15-20 sec, then half of them are loaded correctly but the rest stops loading with 404 HTTP error. If I zoom out and zoom in again, sometimes that 404's tiles will render correctly.

![image](https://user-images.githubusercontent.com/105068401/212838828-5b798e8e-005d-44f7-8c01-38640039cca4.png)
**Server details**: 
- 8 CPU,
- 64 GB RAM,
- SSD 850 GB,
- Europe map imported.

**Run command:**
```bash
 docker run -p 8888:80 -v osm-data:/data/database/ -e ALLOW_CORS=enabled -e THREADS=8 -e "OSM2PGSQL_EXTRA_ARGS=-C 51200" -e AUTOVACUM=off --shm-size="50000m" -d overv/openstreetmap-tile-server run
```
**Postgresql config file:**
```
# Suggested minimal settings from
# https://ircama.github.io/osm-carto-tutorials/tile-server-ubuntu/

shared_buffers = 2GB
min_wal_size = 1GB
# max_wal_size = 2GB # Overridden below
maintenance_work_mem = 10GB

# Suggested settings from
# https://github.com/openstreetmap/chef/blob/master/roles/tile.rb#L38-L45

max_connections = 250
temp_buffers = 32MB
work_mem = 256MB
wal_buffers = 1024kB
wal_writer_delay = 500ms
commit_delay = 10000
# checkpoint_segments = 60 # unrecognized in psql 10.7.1
max_wal_size = 2880MB
random_page_cost = 1.1
track_activity_query_size = 16384
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02

listen_addresses = '*'
autovacuum = on
```

What else can I do?

**Comment by nielsole** [comment]
You can look at increasing ModTileMissingRequestTimeout

**Comment by hajcik1** [comment]
404 problem fixed, thanks. But still, rendering tiles at > 10 zoom sometimes takes few minutes. Server has solid hardware and database is optimized. No error logs.

**Comment by Istador** [comment]
Strange, in my experience rendering the tiles on higher zoom levels is way faster to render than on lower levels, once the lower levels are rendered (because of meta tiles). Because a smaller area needs to fetch and process less data from the database for the wanted area.

---

> -e "OSM2PGSQL_EXTRA_ARGS=-C 51200"

Not necessary anymore, because without updates enabled `osm2pgsql` isn't called anymore. (It is only used on `import` or during updates.)
Also: Why 51 GB ???

---

>`--shm-size="50000m"

50 GB for the shared memory?
Is that necessary or recommended somewhere to set it this high?
I'd recommend setting it to `3g` based on your `shared_buffers` setting of 2 GB.

---

> work_mem = 256MB

Together With `THREADS=8` that can result in a maximum memory usage by the database of:

```
3 + (1 + 8 threads) x 14 tables = 129 connections
129 connections x 256 MB work_mem = 90.4 GB
```

That is more than the 64 GB that your system has and can result in your database being oom killed under load.
