### ISSUE TITLE
til-server automatic update: how to do?

### ISSUE THREAD

**Issue by rdipalmadac** [Overv/openstreetmap-tile-server#417]
Hi.
Up until now I have used the tile-server that I had built with the following run script:
`docker run -e DOWNLOAD_PBF=https://download.geofabrik.de/europe/italy-latest.osm.pbf  -e DOWNLOAD_POLY=https://download.geofabrik.de/europe/italy.poly -v osm-data:/data/database/ -v osm-tiles:/data/tiles/ overv/openstreetmap-tile-server import
`
This is the container run script:
`docker run --name osm-map -p 8000:80 -v osm-data:/data/database/ -v osm-tiles:/data/tiles/ d overv/openstreetmap-tile-server  run`.
Can I get the update since I didn't specify the 'ENABLED' clause when I imported the maps?
For my needs I pre-generated the tiles up to the 19th zoom level, will all the tiles be updated?
How can I understand that the update has occurred?
Thanks for any help

**Comment by Istador** [comment]
To use the automatic updates, you need to enable it for the `import` by providing the `-e UPDATES=enabled` environment variable.
- https://github.com/Overv/openstreetmap-tile-server?tab=readme-ov-file#automatic-updates-optional

Given that you had it enabled when you made the `import` you also need to enable it for the `run` command by providing the `-e UPDATES=enabled` environment variable.
- https://github.com/Overv/openstreetmap-tile-server?tab=readme-ov-file#enabling-automatic-updating-optional

Enabling automatic updates after the `import` is already done is not possible (because during the `import` it needs to detect and remember the current state, to only download differential updates later).

**Comment by rdipalmadac** [comment]
Many thanks
