### ISSUE TITLE
Can I import from multiple .osm.pbf files ? 

### ISSUE THREAD

**Issue by iksheth** [Overv/openstreetmap-tile-server#50]
Hi I am trying to import whole United states, but while it requires much more memory then i have. I thought why not import it in sequence ? Is there any way I can import it one by one ? currently it is replacing old map data.

**Comment by Istador** [comment]
Yes, it is possible to append data to the database one by one with `osm2pgsql --append` instead of `osm2pgsql --create` (which is happening during `import`).

But as I mentioned [here](https://github.com/Overv/openstreetmap-tile-server/issues/2#issuecomment-468008764), it takes much longer (by orders of magnitude) than doing it in one step.

Try first to reduce the memory limit of the process and run with fewer threads (more threads multiply the memory demand).
