### ISSUE TITLE
add overpass api

### ISSUE THREAD

**Issue by abdozzahra** [Overv/openstreetmap-tile-server#74]
can you please add overpass api to docker image?

**Comment by Overv** [comment]
I think that the overpass API is beyond the scope of this image since it is specifically a tile server. However, the database within could be used by an additional image to serve the overpass API as well.

**Comment by abdozzahra** [comment]
tnx , is there anyway to add new nodes to the map? I have a csv with node namde,node id,lat,long,tag and I have to show them on map, right now docker image is up, postgresql is up , country is rendered with 16 layers zoom, but had no success in adding nodes
seems by mistake,I was going to use overpass API
can you please guide?

**Comment by Overv** [comment]
I don't have a lot of experience with tooling around OSM, but you could write a bit of code to just insert them into the database. Another option is to convert them to OSM format and append them after the existing import, see #50.

**Comment by Istador** [comment]
Depending on your use case, it might be easier/better to add them to your application (e.g. as an extra layer in leaflet).

Especially if you want them to be interactive (e.g. click on them to display additional data) or you just need a handful of nodes.

If the amount of items is really big, then instead of passing all POI at once to the application, it might be better to have an additional endpoint that returns only the results on the currently shown map area and groups them on lower zoom levels into one marker.

---

If you really need them to be rendered on the image files (tiles), then you have to re-render those images that you already have after adding them. At least on those tiles where they are visible.

Adding them can be done in several ways:

1.) I'd advise against converting them to the OSM format and appending them. Simply for the reason to keep your application data separated from the osm data. E.g. if you'd add your data to the existing database tables via the import/append, you'd need to give them an unique `osm_id`, but that might overlap with the official IDs sooner or later when updating the data in the database.

2.) You can add them to the postgresql database into a new table that you create (using `psql`). Then you can modify the style of the map to render them. Basically you define the SQL query to select the data and say how and what to render (e.g. lines, polygons, images, etc.).

3.) Alternatively to adding them to the database, the style also has the possibility to use files as a data source directly. For example, the default carto style does this for the [oceans](https://github.com/gravitystorm/openstreetmap-carto/blob/7d478be24f150363e020c723b17b5fb697f22b51/project.mml#L252-L269). I don't know if it works with csv directly.

**Comment by abdozzahra** [comment]
tnx for both respond
case fixed by "leaflet.geocsv"
