### ISSUE TITLE
Documentation about initial server settings

### ISSUE THREAD

**Issue by chivi94** [Overv/openstreetmap-tile-server#88]
I had some problems with the file initial config of the server, to adapt the docker option to my own, and it was because of the entrypoint of the dockerfile. I did a docker-compose, and the issue is:
## Expected behavior

To set up the server i would like to only execute the command "docker-compose up", without specifying the command execution mode
## Actual behavior

Now, it's neccesary to execute docker-compose up with import or run, like this:

- docker-compose run service [run|import]

**Comment by Istador** [comment]
You can specify the `run` command inside your `docker-compose.yml` file. Then you can start the service by just calling `docker-compose up`.

Only the initial database import needs to be done once manually before starting the service.

See the (non-productive) example in issue #71.

---

Keep in mind, that there is no "official" `docker-compose.yml` for this image, only the plain `docker` commands listed in the `README.md`.

The behavior of the entrypoint when no command is given could be changed. It could automatically start the `import` the first time the container is started when there is no database yet and `run` the service directly after that. But that's a task better to be handled manually because it might take hours/days/weeks depending on the import file size and the server specs.

**Comment by Istador** [comment]
I think I linked to the wrong issue 10 days ago. It should be issue #18 and not pull request 71.
